(function(a,u,n){function k(a,b){a.super_=b;c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a}function c(){}function d(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}function t(a,b){return(b=b||n)&&b.getElementById&&b.getElementById(a)}function w(a,b){var c=b?a.substr?t(a):a:n;return c?c.getElementsByTagName(b||a):[]}function v(a,b){return~(" "+a.className+" ").indexOf(" "+b+" ")}function K(a,b){v(a,b)&&(a.className=(" "+a.className+" ").replace(" "+b+" "," ").slice(1,
-1),K(a,b))}function J(a){var c=a.offsetTop,Q=a.offsetLeft,d,e=b.curCSS,f="static"!=e(a,"position");c||(c=(parseFloat(e(a,"marginTop"))||0)+(f?parseFloat(e(a,"top"))||0:0));Q||(Q=(parseFloat(e(a,"marginLeft"))||0)+(f?parseFloat(e(a,"left"))||0:0));f&&a.getBoundingClientRect&&(d=b.offset(a,!0));!c&&d&&(c=d.top);!Q&&d&&(Q=d.left);return{top:c,left:Q}}function C(a){var b={relativeX:a[A[0]],relativeY:a[A[1]]};if(null==a.pageX&&null!=a.clientX){var c=n.documentElement,d=n.body;b.pageX=a.clientX+(c&&c.scrollLeft||
d.scrollLeft||0);b.pageY=a.clientY+(c&&c.scrollTop||d.scrollTop||0)}else b.pageX=a.pageX,b.pageY=a.pageY;return b}function I(a,c){if(!(a=a.parentNode))return!1;var d=a.ownerDocument,e=d.body,f=b.curCSS,g;c&&(c+=1);if(u.$sf)return!0;if(b.isIE&&(8>d.documentMode||"BackCompat"==d.compatMode))return!1;for(;a&&a!=e;){if("hidden"==f(a,"overflow"))return!1;if("fixed"==f(a,"position"))break;else if(c&&(g=parseInt(f(a,"z-index"),10))&&g<c)return!1;a=a.parentNode}return!0}function h(){for(var a=0,b=[];a<W.length;a++)"complete"!=
W[a].document.readyState&&b.push(W[a]);if(!(W=b).length||3E4<(new Date).getTime()-E){D=clearInterval(D);for(a=0;a<P.length;a++)P[a]();P=[];W=[]}}function p(a,b){var c=Math.max(a.x,b.x),d=Math.max(a.y,b.y),e=Math.min(a.x+a.width,b.x+b.width)-c,f=Math.min(a.y+a.height,b.y+b.height)-d;return 0<e&&0<f?{x:c,y:d,width:e,height:f}:{x:0,y:0,width:0,height:0}}function q(a,c,e,f){var g=function(a){f&&f.apply(a,arguments)},h=w(e,"head"),h=h&&h[0];if(!h)try{throw Error("Can't find head tag.");}catch(m){g(m)}var l=
c.src||c.href,k=l.replace(/[^\da-z_-]/gi,"_"),p=e.adformId||b.gid("doc_"),r=p+"|"+k,q=X[r],k=b.byTag(e,a),n=0,t=k.length;e.adformId=e.adformId||p;if(q)q.loaded?g():q.callbacks.push(g);else{for(;n<t;++n)if(k[n].src==l||k[n].href==l){g();return}X[r]=q={doc:e,src:l,callbacks:[g]};var u=e.createElement(a),v;d(u,c);f&&(v=function(a){u.onload=u.onreadystatechange=u.onerror=null;a?X[r]=null:q.loaded=1;var b=q.callbacks;n=0;for(t=b.length;n<t;++n)b[n](a)},u.onload=function(){v()},u.onreadystatechange=function(){"complete"==
u.readyState&&v()},u.onerror=function(){try{throw Error("Failed to load script: "+l);}catch(a){v(a)}});setTimeout(function(){h.insertBefore(u,h.firstChild)},400)}}a.Log||(a.Log={});a.Log.pushMessage||(a.Log.pushMessage=function(){});a.Log.sendMessage||(a.Log.sendMessage=function(){});a.RMB=a.RMB||{};var e=a.RMB,b=e.lib||(e.lib={});a.lib||(a.lib=b);b.inherit=k;b.define=function(a,b,c){c&&k(a,b);c(a,a.prototype)};b.gid=function(a){var b=+new Date;return(a||"")+(b+b*~~(1E4*Math.random())).toString(36)};
b.byId=t;b.byTag=w;b.bind=function(a,b){return function(){return b.apply(a,arguments)}};b.extend=d;b.isMouseLeave=function(a,b){if(!a||"mouseout"!=a.type)return!0;for(var c=a.relatedTarget||a.toElement,d,e=b.length;c;){for(d=0;d<e;d++)if(b[d]==c)return!1;c=c.parentNode}return!0};b.singleCall=function(a){function b(){g=!1;var a=d,Y=c,f=e;c=d=e=null;a&&a.apply(Y,f)}var c,d,e,g;return function(h,l){c=h;d=l;e=f.call(arguments,2);l&&!g?g=setTimeout(b,a):!l&&g&&(clearTimeout(g),g=!1)}};b.onload=function(a,
b){try{do{if(a[M])break;a[M]=!0;"complete"!=a.document.readyState&&(W.push(a),D||(E=(new Date).getTime(),D=setInterval(h,200)))}while(a!=a.parent&&(a=a.parent))}catch(c){}D?P.push(b):setTimeout(b,0)};b.overlap=p;b.overlapElem=function(a,c){var d=b.offset(a),e=b.offset(c);return p({x:d.left,y:d.top,width:a.offsetWidth,height:a.offsetHeight},{x:e.left,y:e.top,width:c.offsetWidth,height:c.offsetHeight})};b.hasClass=v;b.addClass=function(a,b){v(a,b)||(a.className+=" "+b)};b.removeClass=K;b.loadScript=
function(a,b,c){q("script",{src:b,type:"text/javascript"},a,c)};b.loadCSS=function(a,b){q("link",{href:b,type:"text/css",rel:"stylesheet"},a)};b.navigator=u.navigator;b.isTMX=function(a){try{var b=a.document,c=b&&b.body;return c&&v(c,"tmx")}catch(d){}return!1};b.isolate=function(a,b){var c=a.__adform_isolate;if(!c){var d=a.document,c=w(d,"head")[0],d=d.createElement("script");d.type="text/javascript";d.text='function __adform_isolate(f){new Function("window","("+f+")(window)")(window)}';c.insertBefore(d,
c.firstChild);c.removeChild(d);c=a.__adform_isolate}c?c(b):(new Function("window","("+b+")(window)"))(a)};var f=Array.prototype.slice;b.addEvent=function(a,b,c){return a[N]?a[N](b,c,!1):a[g]?a[g]("on"+b,c):!1};b.removeEvent=function(a,b,c){return a[H]?a[H](b,c,!1):a[r]?a[r]("on"+b,c):!1};var N="addEventListener",H="removeEventListener",g="attachEvent",r="detachEvent",m=/([A-Z])/g,z=/^-?\d+(?:px)?$/i,F=/^-?\d/;a=n.defaultView;b.curCSS=a&&a.getComputedStyle?function(a,b){var c=a.ownerDocument.defaultView;
if(c&&(c=c.getComputedStyle(a,null)))return c.getPropertyValue(b.replace(m,"-$1").toLowerCase())||a.style[b]}:n.documentElement.currentStyle&&function(a,b){var c,d,e,f=a.currentStyle&&a.currentStyle[b];if(!z.test(f)&&F.test(f)){c=(e=a.style).left;if(d=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;e.left="fontSize"===b?"1em":f||0;f=e.pixelLeft+"px";e.left=c;d&&(a.runtimeStyle.left=d)}return""===f?"auto":f};var l=function(){function a(){return a}var b=n.body,c=n.createElement("div"),
d;d=["position:absolute;top:0;left:0;margin:0;padding:0;border:0;width:1px;height:1px;"].pop();c.innerHTML='<div style="'+d+'visibility:hidden"><div style="'+d+'border:5px solid #000"><div style="margin:0"></div></div><div style="'+d+'"><div style="'+d+'position:fixed;top:20px;"></div></div><div style="'+d+'position:relative;border:5px solid #000;overflow:hidden"><div style="margin:0"></div></div><table style="'+d+'border:5px solid #000" cellpadding="0" cellspacing="0"><tr><td></td></tr></table></div>';
b.insertBefore(c=c.firstChild,b.firstChild);d=c.childNodes;a.dnab=5!==d[0].firstChild.offsetTop;a.sfp=20===d[1].firstChild.offsetTop;a.sbfonv=-5===d[2].firstChild.offsetTop;a.dabftac=5===w(c,"td").offsetTop;b.removeChild(c);b=c=d=null;return l=a},G=/^t(?:able|d|h)$/i;b.offsetFromWindow=function(a){var c,d,e,f;d=a&&a.ownerDocument;if(!d)return null;e=d.documentElement;if("getBoundingClientRect"in e){try{c=a.getBoundingClientRect(),f=e.getBoundingClientRect()}catch(g){}if(!c)return{top:0,left:0};if(0<
f.left||0<f.top)c.top-=f.top,c.left-=f.left;return{top:c.top,left:c.left}}c=d.defaultView||d.parentWindow;f=d.body;if(a===d.body)return J(a);a=b.offset(a);d=c&&c.pageYOffset||e.scrollTop||f.scrollTop;e=c&&c.pageXOffset||e.scrollLeft||f.scrollLeft;a.top-=d;a.left-=e;return a};b.offset="getBoundingClientRect"in n.documentElement?function(a,b){var c,d=a&&a.ownerDocument;if(!d)return null;if(!b&&a===d.body)return J(a);try{c=a.getBoundingClientRect()}catch(e){}if(!c)return{top:0,left:0};var f=d.body,d=
d.documentElement;return{top:c.top+(d.scrollTop||f.scrollTop)-(d.clientTop||f.clientTop||0),left:c.left+(d.scrollLeft||f.scrollLeft)-(d.clientLeft||f.clientLeft||0)}}:function(a){var b=a&&a.ownerDocument;if(!b)return null;if(a===b.body)return J(a);var c,d=a.offsetParent,e=b.documentElement,f=b.body;c=(b=b.defaultView)?b.getComputedStyle(a,null):a.currentStyle;for(var g=a.offsetTop,h=a.offsetLeft,k=l();(a=a.parentNode)&&a!==f&&a!==e&&(!k.sfp||"fixed"!==c.position);)c=b?b.getComputedStyle(a,null):a.currentStyle,
g-=a.scrollTop,h-=a.scrollLeft,a===d&&(g+=a.offsetTop,h+=a.offsetLeft,!k.dnab||k.dabftac&&G.test(a.nodeName)||(g+=parseFloat(c.borderTopWidth)||0,h+=parseFloat(c.borderLeftWidth)||0),d=a.offsetParent),k.sbfonv&&"visible"!==c.overflow&&(g+=parseFloat(c.borderTopWidth)||0,h+=parseFloat(c.borderLeftWidth)||0);if("relative"===c.position||"static"===c.position)g+=f.offsetTop,h+=f.offsetLeft;k.sfp&&"fixed"===c.position&&(g+=Math.max(e.scrollTop,f.scrollTop),h+=Math.max(e.scrollLeft,f.scrollLeft));return{top:g,
left:h}};b.client=function(a){var b,c,d,e;a=a.ownerDocument||a;c=a.defaultView||a.parentWindow;d=a.documentElement;e=a.body;c.innerWidth?(a=c.innerWidth,b=c.innerHeight):d?(a=d.clientWidth,b=d.clientHeight,a&&e.clientHeight==e.offsetHeight||(a=Math.min(a||123456789,e.clientWidth||123456789),b=Math.min(b||123456789,e.clientHeight||123456789))):(a=e.clientWidth,b=e.clientHeight);return{left:c&&c.pageXOffset||d&&d.scrollLeft||e&&e.scrollLeft||0,top:c&&c.pageYOffset||d&&d.scrollTop||e&&e.scrollTop||0,
width:a,height:b}};b.isArray=Array.isArray||function(a){return"[object Array]"==Object.prototype.toString.call(a)};var A=[["offsetX","offsetY"],["layerX","layerY"]];b.getMousePos=function(a){for(var c;c=A.shift();)if("undefined"!=typeof a[c[0]]){A=c;break}c||(A=["x","y"]);b.getMousePos=C;return C(a)};var V=n.createElement("div");b.html=function(a,b){var c=!b&&V||b.createElement("div");c.innerHTML=a;return c.firstChild&&c.removeChild(c.firstChild)};a=b.navigator;var S=a.vendor;a=a.userAgent;var U=
/Apple Computer/i.test(S),e=/Google/i.test(S),L=b.isIPad=/iPad/i.test(a),x=b.isIPhone=/iPhone/i.test(a),B=b.isIOS=L||x,R=b.isTouch="ontouchstart"in n.documentElement||"ontouchstart"in u,L=b.isOrientation="orientation"in u,x=b.isAndroid=!B&&/Android/i.test(a);b.isAndroidApp=x&&!/^(?:Opera|Mozilla)/i.test(a);var O;b.isIOSF=B&&(O=/\sos\s(\d+)_\d+/i.exec(a))&&(O=4<O[1]>>0);var y=b.isMobile=/Mobile|Mobi|Tablet|Nokia/i.test(a)||R;O=b.isIE=/msie|Trident/i.test(a);R=b.isFF=/Firefox[\/.]+[^\s]/i.test(a);b.isMACOS=
/Mac OS X/i.test(a);(b.isWinPhone=O&&y&&/Phone/gi.test(a))&&(y=/Windows Phone (OS )?(\d+[\.\d]*)/i.exec(a))&&y[2]&&(b.winPhoneVer=parseFloat(y[2]));var y=b.isOpera=/Opera/i.test(a),aa=b.isOperaMobile=/Opera\s(?!Mini)/i.test(a),ba=b.isOperaMini=/Opera\sMini/i.test(a),S=b.isOperaWebKit=/OPR/i.test(a)&&/Opera Software/i.test(S),B=b.isChrome=/(Chrome|CriOS)+\/[\d\.]+\s/i.test(a)&&(B?U:e),U=b.isSafari=!/Chrome|CriOS|Skyfire/i.test(a)&&/Safari+\/[\.\d]+$/i.test(a)&&U,e=b.isInternet=x&&!B&&L&&/Safari\/[\.\d]+$/i.test(a)&&
e;b.isEdge=/Edge\/[\.\d]+$/i.test(a);b.isAfmaSDK=/afma-sdk/i.test(a);var ca=O?"msie":R?"firefox":aa?"operaMobile":ba?"operaMini":y?"opera":S?"operaWebKit":B?"chrome":U?"safari":e?"internet":!1;b.browser=function(){return ca};b.isIE&&("Microsoft Internet Explorer"==b.navigator.appName&&/MSIE (\d+[\.\d]*)/i.exec(a)||/rv:(\d+[\.\d]*)/i.exec(a))&&(b.ieVersion=parseFloat(RegExp.$1));b.testPlace=b.isIE&&8>b.ieVersion?function(){return!1}:I;b.isSafari&&(a=/Version.([\d.]+)/.exec(a),b.safariVersion=parseFloat(a&&
a[1]));var W=[],P=[],M="__adform_onload",D,E,X={}})(Adform=window.Adform||{},window,document);
(function(a){function u(){}a.RMB=a.RMB||{};a.RMB.EventEmitter=u;var n=Array.prototype.slice;a=u.prototype;a.emit=function(a){var c=this._events,d=!1,t=arguments;if(c&&(c=c[a]))if("function"==typeof c){switch(t.length){case 1:c.call(this);break;case 2:c.call(this,t[1]);break;case 3:c.call(this,t[1],t[2]);break;case 4:c.call(this,t[1],t[2],t[3]);break;default:c.apply(this,n.call(t,1))}d=!0}else if(c.length){for(var t=n.call(t,1),c=c.slice(),d=0,w=c.length;d<w;d++)c[d].apply(this,t);d=!0}else delete this._events[a];
return d};a.on=function(a,c){this._events||(this._events={});this.emit("newListener",a,c);var d=this._events;d[a]?"function"==typeof d[a]?d[a]=[d[a],c]:d[a].push(c):d[a]=c;return this};a.once=function(a,c){var d=c._once;d?d._times++:(d=c._once=function(){this.off(a,d);1>--d._times&&delete c._once;return c.apply(this,arguments)},d._times=1);return this.on(a,d)};a.off=function(a,c){if(!this._events||!this._events[a])return this;var d=this._events,t=d[a];if(t==c)return delete d[a],this;c&&c._once&&this.off(c._once);
if("function"==typeof t)return this;if(2>t.length&&t[0]==c)return delete d[a],this;for(var n=0,v=t.length,u=[];n<v;n++)t[n]!=c&&u.push(t[n]);u.length!=v&&(u.length?d[a]=u:delete d[a]);return this};a.clear=function(a){a?this._events&&this._events[a]&&delete this._events[a]:delete this._events;return this};a.list=function(a){this._events||(this._events={});var c=this._events;c[a]?"function"==typeof c[a]&&(c[a]=[c[a]]):c[a]=[];return c[a]}})(Adform=window.Adform||{});
(function(a,u,n){function k(a){return parseInt(a,10)?a:0}function c(){}function d(a,c,k){function d(){q=!1;var a=p;p=[];k(function(b){for(var f=0;f<a.length;f++)if(b)a[f][1](b);else h(a[f][0],a[f][1])})}function h(e,b){var f=!1;c(e,function(){f=!0;b.apply(this,arguments)});f||(p.push([e,b]),q||(q=setTimeout(d,a)))}var p=[],q=!1;return h}function t(a,c,k){var d=a["@id"]||0,h;h=a["@pdata"]||"";var p,q,e={$id:d,$name:a["@name"]||"default",$link:k.replace(/adfibeg=\d+/,h?"pdata="+h:"adfibeg="+d),$pdata:h};
if(a.TextVars)for(k=0,d=a.TextVars.TextVar,h=d.length,v.isArray(d)||(d=[d],h=1);k<h;k++)p=d[k],q=p["@name"],p=p["@value"],e[q]=p,"product_deeplink"==q&&(e.$link+=";cpdir="+encodeURIComponent(p));if(a.Graphics)for(k=0,d=a.Graphics.Graphic,h=d.length,v.isArray(d)||(d=[d],h=1);k<h;k++)p=d[k],e[p["@name"]]=c+p["@value"]+"?assetID="+p["@assetID"]+"&av="+p["@av"];return e}var w=a.AdMessage||(a.AdMessage={}),v=a.lib;w.build=function(a){function n(){var a=L?L.length:0;return{total:a,totalPages:Math.ceil(a/
q),pageSize:q,ids:L||[],limit:p}}function C(a,b,x){w.load(z[a]+"&"+b,function(a,b){if(a)x(a);else{var f=r,y=g,m=b.root,B={};if(m.TextVars||m.Graphics)B[0]=t(m,f,y);if(m.Groups){var Y=0,T=m.Groups.Group,Q;v.isArray(T)||(T=[T]);for(Q=T.length;Y<Q;Y++){var Z=t(T[Y],f,y);B[Z.$id]=Z}}f=m.GroupIds?m.GroupIds.split(","):[];x(null,{ids:f,items:B,total:f.length})}})}function I(a){if(a)for(var b in a)a.hasOwnProperty(b)&&(U[b]=a[b])}var h=u.dhtml&&dhtml.getVar()||{},p=k(a.limit)||100,q=k(a.pageSize)||1,e=k(a.cid||
h.cid),b=k(a.tid||h.tid),f=k(a.tv||h.tv)||+new Date,N=k(a.bn||h.bn),H=a.gid||h.gid||0,g=a.clickTAG||"",r=(a.statics||a.domain||h.staticDomain||h.domain).replace(/\/+$/,""),m=(a.domain||h.domain).replace(/(\w+:\/\/[^\/]+\/).*/,"$1"),z={adMessage:m+"Serving/AdMessage/?",recommendations:m+"dco/recommendations/?",products:m+"dco/products/?"},e="aid="+e+"&tid="+b+"&tv="+f,b=k(a.icid||h.icid)||"0",f=h.unloadID||"0",m=h.geo||"0;0;0",F=a.eshopId||h.trackingSetupId||"0",l=h.ADFbanID||"0",G=k(a.rotseqno||h.rotseqno),
A=a.smid||h.smid,V=a.dcoEngineId||h.dcoEngineId;h.ptid&&(e+="&ptid="+h.ptid);h.paid&&(e+="&paid="+h.paid);b&&(e+="&icid="+b);F&&(e+="&eid="+F);G&&(e+="&rotseqno="+G);A&&(e+="&smid="+A);V&&(e+="&dco="+V);l&&(e+="&bnrid="+l);f&&(e+="&intid="+f);m&&(e+="&geo="+m.split(";").join(","));for(var S in z)z[S]+=e;var U={},L,x=0,B=d(100,function(a,b){var g=a*q,f=g+2*q;x=Math.max(x,f);if(L)if(g=L.slice(g,f),g.length)b(null,g,n());else try{throw Error("AdMessage page not found.");}catch(r){b(r)}},function(a){C(V?
"recommendations":"adMessage","bn="+N+"&gcnt="+p+"&pgsz="+Math.min(x,p),function(b,g){if(b)a(b);else if(I(g.items),(L=g.ids)&&L.length)a();else try{throw Error("AdMessage template doesn't contain groups.");}catch(x){a(x)}});x=0}),R={},O=[],y=d(100,function(a,b){for(var g=a._test||0,x=[],f=0,r=a.length,y,m;f<r;f++)(m=U[y=a[f]])?x.push(m):R[y]||(R[y]=!0,O.push(y));a._test=++g;if(x.length==a.length)b(null,x,n());else if(4<g)try{throw Error("AdMessage group"+((1<a.length?'s "':' "')+a.join(", "))+'" not found.');
}catch(B){b(B)}},function(a){O.length?C(V?"products":"adMessage","bn="+N+"&gid="+O.join(","),function(b,g){R={};b?a(b):(I(g.items),a())}):setTimeout(function(){a()},100);O=[]});return{setProperties:function(a){var b=a.pageSize>>0||q;a=a.limit>>0||p;0<a&&(p=a);0<b&&(q=Math.min(b,p))},getProperties:n,getPage:function(a,b){B((a>>0)-1,function(a,g){a?b(a):(y(g.slice(0,q),b),y(g.slice(q),c))})},getItems:function(a,b){y(v.isArray(a)?a:[a],b)},getDefault:function(a){y([H],function(b,g,x){a(b,g&&g[0],x)})}}};
w.load=function(a,k){var d=v.gid("adform_com_"),c=n.createElement("script"),h=function(){q();try{throw Error("AdMessage load error.");}catch(a){k(a)}},p=function(a){q();k(null,a)},q=function(){c.parentNode.removeChild(c);u[d]=c.onerror=c.onload=h=p=q=c=null};c.type="text/javascript";c.src=a+"&format=json&callback="+encodeURIComponent(d);c.onload=c.onerror=function(){setTimeout(h,1E3)};u[d]=p;var e=v.byTag(n,"script")[0];e.parentNode.insertBefore(c,e)}})(Adform=window.Adform||{},window,document);
(function(a,u,n,k){function c(){}function d(a){for(var b=p.length;0<b--;)if(p[b][0]==a)return p[b][1]}function t(a,c,k){function g(g){if(g&&n)b(n,"touchstart",C);else if(!n)try{(n=a.defaultView.frameElement)&&e(n,"touchstart",C)}catch(r){}}var r=d(a),m,z,F,l;r?m=r._:p.push([a,r={_:m=new h,_destroy:function(){m.clear();delete this._;delete this._destroy;for(var b in this)if("function"==typeof this[b])this[b]();for(b=p.length;0<b--;)if(p[b][0]==a){p.splice(b,1);break}}}]);var G,A,q,n,t,u,x,B,R,O;I.isIOS&&
a.defaultView.frameElement&&{click:1,mousedown:1,mouseup:1}[c]&&e(k,c,C);if(!r[c])switch(c){case "swipe":G=function(a){if(q=K(m,a.target,"swipe")[0])a.preventDefault(),(a=a&&a.targetTouches)&&(a=a[0])&&(t=a.pageX,x=a.pageY,R=(new Date).getTime())};A=function(a){var b=a&&a.targetTouches;q&&(a.preventDefault(),b&&(b=b[0])&&R&&(u=b.pageX,B=b.pageY,O=(new Date).getTime(),.2<Math.sqrt(Math.pow(u-t,2)+Math.pow(B-x,2))/(O-R)&&(a=x-B,b={type:"swipe"},b.directionX=0<t-u?"left":"right",b.directionY=0<a?"up":
"down",b.target=q[1],R=0,v(m,q[1],b))))};e(a,"touchstart",G);e(a,"touchend",A);e(a,"touchmove",A);g();r[c]=function(){b(a,"touchstart",G);b(a,"touchend",A);b(a,"touchmove",A);g(!0)};break;case "hover":a.addEventListener?(z=function(a){a=a.target;l!=a&&w(m,l,l=a)},F=function(a){a=a.relatedTarget;l!=a&&w(m,l,l=a)}):(z=function(b){b=(a.defaultView||a.parentWindow).event.srcElement;l!=b&&w(m,l,l=b)},F=function(b){b=(a.defaultView||a.parentWindow).event.toElement;l!=b&&w(m,l,l=b)});e(a,"mouseover",z);
e(a,"mouseout",F);e(a,"mousemove",z);r[c]=function(){b(a,"mouseover",z);b(a,"mouseout",F);b(a,"mousemove",z);l=null};break;case "click":case "mousedown":case "mouseup":case "touchstart":case "touchmove":case "touchend":z=a.addEventListener?function(a){v(m,a.target,a)}:function(b){b=(a.defaultView||a.parentWindow).event;v(m,b.srcElement,b)},e(a,c,z),r[c]=function(){b(a,c,z)}}return!!r[c]}function w(a,b,c){c=K(a,c,"hover");b=K(a,b,"hover");for(var g=c.length,r=g,m=b.length,e=m-g;0<r--&&c[r][1]==(b[e+
r]&&b[e+r][1]););c.length=g=r+1;b.length=m=e+r+1;var d,l=a._events;if(l){for(e=r=-1;++e<m;)l[d=b[e][0]]&&a.emit(d,b[e][1],"hoverout");for(;++r<g;)l[d=c[r][0]]&&a.emit(d,c[r][1],"hoverin")}}function v(a,b,c,g){g=g||c;b=K(a,b,c.type);c=b.length;for(var r=0,m;m=b[r],r++<c;)a.emit(m[0],m[1],g)}function K(a,b,c){a=a._events;var g,r,m,e=[];if(a)for(;b&&"undefined"!=(m=typeof(r=b.className));)"string"==m&&~r.indexOf("adform-dom-")&&a[g=J(b)+":"+c]&&(e[e.length]=[g,b]),b=b.parentNode;return e}function J(a){a=
a.className;return~a.indexOf("adform-dom-")?a.match(q)[1]:I.gid()}function C(){}a.RMB=a.RMB||{};a=a.RMB;a.DOMEvents=c;var I=a.lib,h=a.EventEmitter,p=[],q=/adform-dom-(\S+)/,e=I.addEvent,b=I.removeEvent;c.has=function(a){return!!{hover:1,mousedown:1,mouseup:1,click:1,swipe:1,touchstart:1,touchmove:1,touchend:1}[a]};c.on=function(a,b,c){var g=a.ownerDocument;if(t(g,b,a)){var r=J(a);I.addClass(a,"adform-dom-"+r);d(g)._.on(r+":"+b,c);return!0}return!1};c.off=function(a,b,c){d(a.ownerDocument)._.off(J(a)+
":"+b,c)};c.destroy=function(a){d(a)._destroy()}})(Adform=window.Adform||{},window,document);
var Mustache="undefined"!==typeof module&&module.exports||{};
(function(a){function u(a){return String(a).replace(/&(?!\w+;)|[<>"']/g,function(a){return N[a]||a})}function n(a,b,c,e){e=e||"<template>";for(var d=b.split("\n"),l=Math.max(c-3,0),d=d.slice(l,Math.min(d.length,c+3)),k,f=0,h=d.length;f<h;++f)k=f+l+1,d[f]=(k===c?" >> ":"    ")+d[f];a.template=b;a.line=c;a.file=e;a.message=[e+":"+c,d.join("\n"),"",a.message].join("\n");return a}function k(a,b,c){if("."===a)return b[b.length-1];a=a.split(".");for(var e=a.length-1,d=a[e],k,f,h=b.length,p,q;h;){q=b.slice(0);
f=b[--h];for(p=0;p<e;){f=f[a[p++]];if(null==f)break;q.push(f)}if(f&&"object"===typeof f&&d in f){k=f[d];break}}"function"===typeof k&&(k=k.call(q[q.length-1]));return null==k?c:k}function c(a,b,c,e){var d="";a=k(a,b);if(e){if(null==a||!1===a||h(a)&&0===a.length)d+=c()}else if(h(a))p(a,function(a){b.push(a);d+=c();b.pop()});else if("object"===typeof a)b.push(a),d+=c(),b.pop();else if("function"===typeof a)var f=b[b.length-1],d=d+(a.call(f,c(),function(a){return v(a,f)})||"");else a&&(d+=c());return d}
function d(b,c){c=c||{};for(var d=c.tags||a.tags,k=d[0],f=d[d.length-1],l=['var buffer = "";',"\nvar line = 1;","\ntry {",'\nbuffer += "'],h=[],p=!1,t=!1,u=function(){if(!p||t||c.space)h=[];else for(;h.length;)l.splice(h.pop(),1);t=p=!1},w=[],v,x,B,C=function(a){d=e(a).split(/\s+/);x=d[0];B=d[d.length-1]},K=function(a){l.push('";',v,'\nvar partial = partials["'+e(a)+'"];',"\nif (partial) {","\n  buffer += render(partial,stack[stack.length - 1],partials);","\n}",'\nbuffer += "')},y=function(a,T){var Q=
e(a);if(""===Q)throw n(Error("Section name may not be empty"),b,P,c.file);w.push({name:Q,inverted:T});l.push('";',v,'\nvar name = "'+Q+'";',"\nvar callback = (function () {","\n  return function () {",'\n    var buffer = "";','\nbuffer += "')},H=function(a){y(a,!0)},I=function(a){a=e(a);var T=0!=w.length&&w[w.length-1].name;if(!T||a!=T)throw n(Error('Section named "'+a+'" was never opened'),b,P,c.file);a=w.pop();l.push('";',"\n    return buffer;","\n  };","\n})();");a.inverted?l.push("\nbuffer += renderSection(name,stack,callback,true);"):
l.push("\nbuffer += renderSection(name,stack,callback);");l.push('\nbuffer += "')},J=function(a){l.push('";',v,'\nbuffer += lookup("'+e(a)+'",stack,"");','\nbuffer += "')},N=function(a){l.push('";',v,'\nbuffer += escapeHTML(lookup("'+e(a)+'",stack,""));','\nbuffer += "')},P=1,M,D,E=0,X=b.length;E<X;++E)if(b.slice(E,E+k.length)===k){E+=k.length;M=b.substr(E,1);v="\nline = "+P+";";x=k;B=f;p=!0;switch(M){case "!":E++;D=null;break;case "=":E++;f="="+f;D=C;break;case ">":E++;D=K;break;case "#":E++;D=y;
break;case "^":E++;D=H;break;case "/":E++;D=I;break;case "{":f="}"+f;case "&":E++;t=!0;D=J;break;default:t=!0,D=N}M=b.indexOf(f,E);if(-1===M)throw n(Error('Tag "'+k+'" was not closed properly'),b,P,c.file);k=b.substring(E,M);D&&D(k);for(D=0;~(D=k.indexOf("\n",D));)P++,D++;E=M+f.length-1;k=x;f=B}else switch(M=b.substr(E,1),M){case '"':case "\\":t=!0;l.push("\\"+M);break;case "\r":break;case "\n":h.push(l.length);l.push("\\n");u();P++;break;default:q.test(M)?h.push(l.length):t=!0,l.push(M)}if(0!=w.length)throw n(Error('Section "'+
w[w.length-1].name+'" was not closed properly'),b,P,c.file);u();l.push('";',"\nreturn buffer;","\n} catch (e) { throw {error: e, line: line}; }");f=l.join("").replace(/buffer \+= "";\n/g,"");c.debug&&("undefined"!=typeof console&&console.log?console.log(f):"function"===typeof print&&print(f));return f}function t(a,b){var e=d(a,b),f=new Function("view,partials,stack,lookup,escapeHTML,renderSection,render",e);return function(d,e){e=e||{};var h=[d];try{return f(d,e,h,k,u,c,v)}catch(m){throw n(m.error,
a,m.line,b.file);}}}function w(a,b){b=b||{};return!1!==b.cache?(H[a]||(H[a]=t(a,b)),H[a]):t(a,b)}function v(a,b,c){return w(a)(b,c)}a.name="mustache.js";a.version="0.5.0-dev";a.tags=["{{","}}"];a.parse=d;a.compile=w;a.render=v;a.clearCache=function(){H={}};a.to_html=function(a,b,c,d){a=v(a,b,c);if("function"===typeof d)d(a);else return a};var K=Object.prototype.toString,J=Array.isArray,C=Array.prototype.forEach,I=String.prototype.trim,h;h=J?J:function(a){return"[object Array]"===K.call(a)};var p;
p=C?function(a,b,c){return C.call(a,b,c)}:function(a,b,c){for(var d=0,e=a.length;d<e;++d)b.call(c,a[d],d,a)};var q=/^\s*$/,e;if(I)e=function(a){return null==a?"":I.call(a)};else{var b,f;q.test("\u00a0")?(b=/^\s+/,f=/\s+$/):(b=/^[\s\xA0]+/,f=/[\s\xA0]+$/);e=function(a){return null==a?"":String(a).replace(b,"").replace(f,"")}}var N={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"},H={}})(Mustache);
(function(a,u,n){function k(){if(u.Ready)for(var a=0;a<Ready.length;a++)t(Ready[a]);u.Ready={push:t}}function c(a,b){var g=m;a&&(g="undefined"==typeof m[a]?b:m[a]);return g}function d(a){a=parseInt(a,10);var b=c("videoSources");if(b)for(var g=b.length,f,r=0;r<g;r++)if(f=b[r],f.id==a)return f.file}function t(a){a.call(u);L||(clearTimeout(U),U=setTimeout(function(){L=!0;n.close()},1E3))}function w(a,b){"function"==typeof b&&(a=b);try{throw Error("AdMessage template id is missing");}catch(g){if("function"==
typeof a)a(g);else throw g;}}function v(a,b,f,m){var y=u._Adform&&_Adform.Events;if(y&&y.sendEvent){if(a in F)b=F[a];else if(isNaN(a=parseInt(a,10))||1>a||20<a&&200>a||250<a)throw Error("Custom event id="+a+" must be between 1-20 for engaging and 200-250 for non-engaging events");if(!b)throw Error("Event name is missing");var c=[""];if(f)for(var e in f){var l=e.slice(0,2),d=parseInt(e.slice(2),10);"bv"==l&&0<d&&256>d&&c.push(e+"="+encodeURIComponent(f[e]))}m&&c.push(m);y.sendEvent(r.xId,a,g.assetId,
b,c.join("&"),"Standard HTML");return!0}return!1}function K(a,b){h[a]||(h[a]=Mustache.compile(J(a).text));if(b){if(q.length!=f){for(var g=0;g<q.length;g++)"text/mustache"==q[g].type&&K(q[g].id);f=q.length}return h[a](b,h)}return h[a]}function J(a){return n.getElementById(a)}for(var C=a.RMB.lib,I=C.isArray,h={},p,q=n.getElementsByTagName("script"),e=0,b;e<q.length;e++)if(b=(q[e].src||"").match(/(^.*)rmb\/Adform\.DHTML\.js/)){p=b[1]+"components/";break}var f=0,N=a.RMB.EventEmitter;b=a.RMB.DOMEvents;
var H=u._AdformContent||{},g=H.data||{},r=H.options||{},m=g.flashvars||{},z=new N;a.on=function(){z.on.apply(z,arguments)};a.off=function(){z.off.apply(z,arguments)};a.emit=function(){z.emit.apply(z,arguments)};var F={151:"Previous Product Button Press",150:"Next Product Button Press",143:"Banner Collapse",22:"Other Expands",21:"First Expand",168:"Auto Expands",161:"Hide Expanding Banner Button Press",23:"Close Button Press",25:"Video Play Start",26:"Played 25% Of Video",27:"Played 50% Of Video",
28:"Played 75% Of Video",29:"Video Playback Complete",30:"Play Button Press",31:"Pause Button Press",32:"Stop Button Press",33:"Sound On Button Press",34:"Sound Off Button Press",35:"Full Screen On Button Press",36:"Full Screen Off Button Press",38:"Rewind Button Press","":""};a.EVENT_FIRST_EXPAND=[21,F[21]];a.EVENT_OTHER_EXPAND=[22,F[22]];a.EVENT_CLOSE=[23,F[23]];a.EVENT_COLLAPSE=[143,F[143]];for(e=1;251>e;e++)if(21>e||199<e)a["EVENT_CUSTOM_"+e]=[e,"Custom Event "+e];a.sendRequest=function(a){(new Image).src=
a};a.sendEvent=function(a){var b,g,f=arguments;if(b=I(a)&&1<a.length){for(b=1;b<f.length&&256>b;b++)(g=g||{})["bv"+b]=f[b];b=v(a[0],a[1],g)}return b};a.getClickURL=function(a,b){return c(a||g.defaultClickTAG||"clickTAG",b)||null};a.getLocation=function(){var a=u._Adform&&_Adform.locationInfo||null;a&&(a.lng=a.Longitude,a.lat=a.Latitude);return a};a.getAsset=function(a){return d(a)||null};a.getVar=function(a){return a&&m[a]?m[a]:null};var l=u.dhtml={PREVIOUS_BUTTON_PRESS:151,NEXT_BUTTON_PRESS:150,
CLOSE_BUTTON_PRESS:23,COLLAPSE_EVENT:143,EXPAND_EVENT:22,FIRST_EXPAND_EVENT:21,AUTO_EXPAND_EVENT:168,SUPER_CLOSE_EVENT:161,VIDEO_PROG_0:25,VIDEO_PROG_25:26,VIDEO_PROG_50:27,VIDEO_PROG_75:28,VIDEO_PROG_100:29,PLAY_BUTTON_PRESS:30,PAUSE_BUTTON_PRESS:31,STOP_BUTTON_PRESS:32,SOUND_ON_BUTTON_PRESS:33,SOUND_OFF_BUTTON_PRESS:34,FULL_SCREEN_ON_BUTTON_PRESS:35,FULL_SCREEN_OFF_BUTTON_PRESS:36,REWIND_BUTTON_PRESS:38,byId:J,hasClass:C.hasClass,addClass:C.addClass,removeClass:C.removeClass,mustache:K,sendEvent:function(a,
b,g){if(!(G&&G.callDHTMLEvent&&G.callDHTMLEvent.call(G,a)))return a in F&&(g=null),v(a,b,g)},$sendEvent:v,appendEvents:function(a){for(var b in a)F.hasOwnProperty(b)||(F[b]=a[b]);return F},getVar:c,getAsset:d,width:g.width,height:g.height,collapsedWidth:r.colWidth,collapsedHeight:r.colHeight,external:H.external||{},inscreen:new N,sharedEvents:H.sharedEvents||new N,scriptsBase:r.scriptsBase||p+"../",getState:function(){return H.state?H.state():"visible"},on:b.on,off:b.off,connect:function(a){var b,
g,f=u._Adform&&_Adform.ADFUtilInstance;a=a||m.bn||"x";f=f?f.getRotSeed():{};f.localConnections||(f.localConnections={});b=f.localConnections[a];b||(b=new N,g=[],b.expect=function(a,f){if(g.length>=a)f();else b.once("expect:"+a,f);return b},b.join=function(a){g.push(a);b.emit("member",a);b.emit("expect:"+g.length);return b},b.members=g,f.localConnections[a]=b);return b}},G;try{G=parent.parent.getVPAIDAd&&parent.parent.getVPAIDAd()}catch(x){}G&&(l.vpaid=G,l.external.close=function(){G.callDHTMLEvent&&
G.callDHTMLEvent.call(G,23)});l.sharedEvents.on("newListener",function(a){"pageLoadComplete"==a&&setTimeout(function(){l.external.initPoliteMode()},0)});l.adMessage=m.tid?a.AdMessage.build({limit:100,pageSize:5}):{setProperties:w,getProperties:w,getPage:w,getItems:w,getDefault:w};var A=l.inscreen;l.external.initInScreen&&(l.sharedEvents.on("updateInScreen",function(a){for(var b in a)A.emit(b,A[b]=a[b]);A.emit("change")}),a.on("newListener",function(b){"visibilityData"===b&&(a.off("newListener",arguments.callee),
A.on("change",function(){a.emit("visibilityData",{isVisible:A.visible,visibleArea:A.percent})}))}),A.once("newListener",function(){setTimeout(function(){l.external.initInScreen()},0)}));components=u.preloadQueue||u.components||[];for(var V=components.length,e=0;e<components.length;e++)n.write('<script src="'+(p+"Adform."+components[e]+".js?bv="+(m.bv||Math.random()))+'">\x3c/script>');try{var S=n.defaultView.frameElement;S&&C.addEvent(S,"touchstart",function(){})}catch(x){}l.registerComponent=function(a){for(var b=
0;b<components.length;b++)components[b]==a&&V--;V||k()};V||k();var U,L})(Adform=window.Adform,window,document);
