//v128 (c) 2008-2016 33Across Inc. All Rights Reserved

Tynt=window.Tynt||[];
"undefined"==typeof Tynt.TIL&&"undefined"==typeof Tynt.TCL&&function(){var g=window,e=document,n={distro:"TI-"+(new Date).getTime()};Tynt.TIL=function(){function B(){}function Pa(a,b,c,d){var k=function(a,b,c,d,k){a.size=b||"";a.size?(b=b.split("x"),a.width=b[0],a.height=b[1]):(a.width="0",a.height="0");a.targetId=c||"";a.product=d||"inpage";k?a.distro=k:"inview"==a.product&&(a.distro="RCIV");a.iframeId=null;a.sicWindow=null};22==a.length?(this.publisherId=a,this.options=c||{},k(this,this.options.size||
"1x1",this.options.targetId||"",b)):k(this,a,b,c,d)}function Q(a){var b=Q.options;a=b.parser[b.strictMode?"strict":"loose"].exec(a);for(var c={},d=14;d--;)c[b.key[d]]=a[d]||"";c[b.q.name]={};c[b.key[12]].replace(b.q.parser,function(a,d,e){d&&(c[b.q.name][d]=e)});return c}if(document.body){Date.now||(Date.now=function(){return(new Date).getTime()});var f={_maxRef:800,_idMacro:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",init:function(){this._icUrl=n.protocol+(Tynt.e||"")+"ic.tynt.com";this._debUrl=
n.protocol+(Tynt.e||"")+"de.tynt.com/deb/v2";this._sicUrl=n.protocol+(Tynt.e||"")+"cdn-sic.33across.com/1/javascripts/sic.js";this._apUrl=n.protocol+(Tynt.e||"")+"cdn-ap.33across.com/javascripts/ap.js"},newEle:function(a,b,c,d){d=d||window;a=d.document.createElement(a);b&&this.extend(a,b);c&&this.extend(a.style,c);return a},injectScript:function(a,b,c){b=b||window;a=this.newEle("script",{async:"async",type:"text/javascript",src:a},null,b);this.insertEle(a,c||b.document.getElementsByTagName("script")[0])},
injectSicScript:function(a){this.injectScript(this._sicUrl,window,a)},injectApolloScript:function(){this.injectScript(this._apUrl)},injectSicIframe:function(a,b,c){var d={width:a.width+"px",height:a.height+"px",border:"0 none",margin:"0"};c&&this.extend(d,c);c=this.newEle("iframe",{src:"about:blank",frameBorder:"0",frameSpacing:"0",scrolling:"no"},d);this.insertEle(c,b);a.iframeId=this.eleId(c);a.sicWindow=c.contentWindow;a=c.contentWindow.document;a.open();a.write('<!DOCTYPE html><html><head><style type="text/css">*{margin:0;padding:0;}</style></head><body><script type="text/javascript">window.Tynt = window.parent.Tynt;\x3c/script><script type="text/javascript" src="'+
this._sicUrl+'">\x3c/script></body></html>');a.close()},insertEle:function(a,b){b?"script"==b.tagName.toLowerCase()?b.parentNode.insertBefore(a,b):b.appendChild(a):document.body.appendChild(a)},eleId:function(a){var b=a.id;b||(b="x33x"+Date.now(),a.id=b);return b},injectPixel:function(a,b,c){var d;try{d=e.createElement("img")}catch(k){d=document.createElement("img")}d&&(b&&(d.onload=b),c&&(d.onerror=c),d.src=a)},docUrl:function(){var a,b=null,c;c=e.getElementsByTagName("link");for(a=0;a<c.length;++a)c[a].getAttribute("href")&&
c[a].getAttribute("rel")&&0<=c[a].getAttribute("rel").indexOf("canonical")&&(b=c[a].href);b||(b=this.getMeta("property","og:url","name","original-source"));return b?(0!=b.indexOf("http")&&(a=n.protocol+g.location.host+g.location.pathname,(c=e.getElementsByTagName("base")[0])&&(c=c.getAttribute("href"))&&(a=c),"/"==b.charAt(0)?(c=a.indexOf("/",9),-1<c&&(a=a.slice(0,c))):(c=a.lastIndexOf("/"),a=9<c?a.slice(0,c+1):a+"/"),b=a+b),b):""},getMeta:function(a,b,c,d){var k,l=null,g=null,M=e.getElementsByTagName("meta");
for(k=0;k<M.length;++k)l||M[k].getAttribute(a)!==b?c&&!g&&M[k].getAttribute(c)===d&&(g=M[k].getAttribute("content")||null):l=M[k].getAttribute("content")||null;return l||g},extend:function(a,b){var c,d;for(c=1;c<arguments.length;++c)for(d in arguments[c])arguments[c].hasOwnProperty(d)&&(a[d]=arguments[c][d]);return a},isArray:function(a){return"undefined"!=typeof a&&"[object Array]"===Object.prototype.toString.call(a)},inArray:function(a,b){return 0<=this.indexOf(a,b)},toArray:function(a,b){return Array.prototype.slice.call(a,
b||0)},indexOf:function(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0;c<a.length;++c)if(a[c]===b)return c;return-1},unique:function(a){var b,c={},d=[];for(b=0;b<a.length;++b)c[a[b]]||(c[a[b]]=!0,d.push(a[b]));return d},iframeType:function(){var a=this.iframeEle(),b=0;if(a)a.id&&0<=a.id.search(/google_ads?_i?frame/)?(b=6,f.log(1,"In same-origin iframe from DFP")):(b=5,f.log(1,"In same-origin iframe"));else try{window!=window.top?"undefined"!=typeof window.$sf?(b=4,f.log(1,"In SafeFrame")):(b=3,
f.log(1,"In cross-origin iframe")):f.log(1,"In top window")}catch(c){b=3,f.log(1,"DEBUG: exception 2")}return b},iframeEle:function(a){var b=null;a=a||window;try{b=a.frameElement}catch(c){}return b},iframeTop:function(){var a=window,b=null;try{for(;a!=window.top;)b=a,a=a.parent}catch(c){return null}return b?this.iframeEle(b):null},getTopWin:function(){var a=window;try{for(;a.parent!==a&&a.parent.document;)a=a.parent}catch(b){}return a},jsonDecode:function(a){if("function"!==typeof Array.prototype.toJSON)return JSON.stringify(a);
var b=Array.prototype.toJSON;delete Array.prototype.toJSON;a=JSON.stringify(a);Array.prototype.toJSON=b;return a},getCookie:function(a,b){for(var c=b+"=",d=a.split(";"),k=0;k<d.length;k++){for(var l=d[k];" "==l.charAt(0);)l=l.substring(1,l.length);if(0===l.indexOf(c))return l.substring(c.length,l.length)}return null},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},trunc:function(a,b){var c,d;if(!a||a.length<=b)return a;c=a.substring(0,b);for(d=1;3>=d;++d)if("%"==c.charAt(c.length-d))return c.substring(0,
c.length-d);return c},tyntIds:function(){return this.unique(Tynt).join("~")},log:function(){var a;"undefined"==typeof Tynt.debug&&0<g.location.search.indexOf("__tcdebugmode=1")&&g.console&&g.console.log&&(Tynt.debug=1);1===Tynt.debug&&(a=this.toArray(arguments),1===a[0]&&(a[0]=n.distro),a.unshift("[TC]"),g.console.log.apply(g.console,a))},callIc:function(){var a,b,c,d,k,l,h;if(!g._33Across.state.icDone){g._33Across.state.icDone=1;b=this.getCookie(e.cookie,"tracertraffic");a=g.location.hash;a=/tynt=/.test(a)?
a.match(/tynt=?([^?&$#]*)/)[1]:!1;d=c=this._icUrl+"/b/p?id="+this.tyntIds()+(b?"&et="+b:"")+(a?"&a="+a:"")+("string"==typeof Tynt.b?"&b="+Tynt.b:"")+"&lm="+n.type+"&ts="+Date.now();(a=this.getMeta("property","og:image:url","property","og:image"))&&(d+="&img="+encodeURIComponent(this.trunc(a,255)));k=d;(a=this.getMeta("property","og:title"))&&a!=e.title&&(k+="&ct="+encodeURIComponent(this.trunc(a,127)));l=k;e.referrer&&(a=this.trunc(e.referrer,this._maxRef),l+="&r="+encodeURIComponent(a));h=l;if(a=
e.title||g.location.hostname)a=this.trim(this.trunc(a,200)),h+="&t="+encodeURIComponent(a);b=h;if(a=this.docUrl())a=this.trunc(a,500),b+="&cu="+encodeURIComponent(a);f.callIc.rsp=function(){g._33Across.state.icDone=2};f.log(1,"Calling IC");this.injectPixel(b,f.callIc.rsp,function(){f.injectPixel(h,f.callIc.rsp,function(){f.injectPixel(l,f.callIc.rsp,function(){f.injectPixel(k,f.callIc.rsp,function(){f.injectPixel(d,f.callIc.rsp,function(){f.injectPixel(c,f.callIc.rsp)})})})})})}},callDeb:function(a){if("undefined"==
typeof a){if(g._33Across.state.deDone)return;a=4}g._33Across.state.deDone=!0;0==a||2==g._33Across.state.icDone?(f.log(1,"Calling DEB"+(0==a?" on IC timeout":"")),this.injectScript(this._debUrl+"?id="+this.tyntIds()+"&r="+encodeURIComponent(this.trunc(e.referrer,this._maxRef)),g)):setTimeout(function(){f.callDeb(a-1)},50)}};n.type=f.iframeType();5<=n.type&&(g=f.getTopWin(),e=g.document);g._33Across||(g._33Across={});g._33Across.state||(g._33Across.state={icDone:0,deDone:!1,ivDone:!1});"https:"===g.location.protocol?
(n.isSecure=!0,n.protocol="https://"):(n.isSecure=!1,n.protocol="http://");f.init();if("undefined"===typeof r)var r={afterIpBlockCheck:[],afterDynamicConfig:[],afterCheckModules:[],afterProtectTynt:[],afterDynamicConfigAndDocumentLoaded:[]};var u=function(a,b){if("undefined"!==typeof r&&r.hasOwnProperty(a)&&r[a].hasOwnProperty("length"))for(var c=0;c<r[a].length;c+=1)if("function"===typeof r[a][c])r[a][c](b)};Tynt.settings||(Tynt.settings={_error:0,_pending:!1,_pubId:null,_scUrl:n.protocol+(Tynt.e||
"")+"sc.tynt.com/script/sc/",_settings:{},_copy:null,isReady:function(){return 0===this._error&&null!=this._copy},get:function(){return this._settings},pubId:function(){if(null==this._pubId)for(var a=0;a<Tynt.length;++a)if("string"==typeof Tynt[a]&&22==Tynt[a].length&&0>Tynt[a].indexOf("!")){this._pubId=Tynt[a];break}return this._pubId},download:function(){var a,b;B.adapt(Tynt.cmd);this._pending||this.isReady()||(a=this,Tynt.getConfig=function(){return a.isReady()?a._copy:null},Tynt.sc=function(c){clearTimeout(b);
a._error=c.fl||0;0===a._error?(a._init(c),f.log("Settings downloaded",a._copy),Tynt.cmdFlush()):f.log("ERROR: Settings download failed: ",a._error);a._pending=!1},this.pubId()&&(f.log("Downloading settings"),this._pending=!0,f.injectScript(this._scUrl+this.pubId()+".js"),b=setTimeout(function(){Tynt.sc({fl:1})},1E4)))},_init:function(a){a=a||{};!0===a.d?(Tynt.o&&f.extend(a,Tynt.o),this._ovr(a)):a=Tynt.i||g.tyntVariables||{};this._def();f.extend(this._settings,a);this._val();this._copy="undefined"!==
typeof JSON&&"function"===typeof JSON.parse&&"function"===typeof JSON.stringify?JSON.parse(f.jsonDecode(this._settings)):this._settings},_ovr:function(a){if(f.isArray(Tynt.overrides))for(var b=0;b<Tynt.overrides.length;b++)"object"===typeof Tynt.overrides[b]&&f.extend(a,Tynt.overrides[b])},_def:function(){this._settings.d=!0;this._settings.a=!0;this._settings.ad=!0;this._settings.aw=0;this._settings.cc=0;this._settings.b=!1;this._settings.ap="Read more:";this._settings.as="";this._settings.st=!1;
this._settings.su=!0;this._settings.w=!1;this._settings.f=!1;this._settings.ss=""},_val:function(){this._settings.a||(this._settings.a=!1);6<this._settings.cc&&(this._settings.cc=0);8>this._settings.aw&&(this._settings.aw=8);this._settings.su||(this._settings.su=!1);this._settings.w&&!this._twUser(this._settings.w)&&(this._settings.w=!1);this._settings.f&&!this._fbUser(this._settings.f)&&(this._settings.f=!1);0<this._error&&(this._settings.a=!1,this._settings.b=!1)},_twUser:function(a){return/^\w{1,15}$/.test(a||
"")},_fbUser:function(a){return/^[\w.]{2,}$/.test(a||"")}});"undefined"==typeof Tynt.cmd&&(Tynt.cmd=[]);B.prototype.push=function(){B.adapt(arguments);B.exec(arguments)};B.exec=function(a){f.log("Executing commands",a);try{for(var b=0;b<a.length;++b)if("function"===typeof a[b])a[b]();else"object"===typeof a[b]&&"function"===typeof a[b].fn&&a[b].fn()}catch(c){f.log("Tynt.cmd ERROR",c)}};B.adapt=function(a){var b,c;if(f.isArray(a))for(b=0;b<a.length;++b)"object"==typeof a[b]&&(c=a[b].publisherId,"string"!=
typeof c||22!=c.length||f.inArray(Tynt,c)||(Tynt.push(c),f.log("Adapted",c)))};"undefined"==typeof Tynt.cmdFlush&&(Tynt.cmdFlush=function(){var a=Tynt.cmd;if(!a||f.isArray(a))Tynt.cmd=new B,a&&0<a.length&&B.exec(a)});Tynt.ads||(Tynt.ads={_slots:[],display:function(a,b,c,d){"string"==typeof a?this.addSlot(new Pa(a,b,c,d)):f.log("ERROR: Invalid product")},getSlot:function(a){return(a=this.getSlots(a))&&0<a.length?a[0]:null},getSlots:function(a){for(var b=[],c=0;c<this._slots.length;++c)this._slots[c].sicWindow===
a&&b.push(this._slots[c]);return 0<b.length?b:null},addSlot:function(a){var b=null,c=Tynt.settings.get(),d="Injecting sic/"+a.product;if(c&&c.sic)if(a.sicWindow=window,"inview"==a.product&&this.ivReady(c,a))this.ivDone(!0),this._slots.push(a),f.log(d,a),f.injectSicScript();else{if("inpage"==a.product&&this.ipReady(c)||"infeed"==a.product&&this.ifReady(c))a.targetId&&(b=document.getElementById(a.targetId)),0<n.type?(this._setIframeId(a),this._slots.push(a),f.log(d,a),f.injectSicScript(b)):b?(this._slots.push(a),
f.log(d+" into iframe",a),f.injectSicIframe(a,b,"infeed"==a.product?{position:"absolute"}:null)):f.log("ERROR: Could not install "+a.product+". Could not find target element",a.targetId)}else f.log("ERROR: settings or .sic undefined",c)},_setIframeId:function(a){var b=f.iframeTop();b&&(a.iframeId=f.eleId(b))},ivDone:function(a){!0===a&&(g._33Across.state.ivDone=!0);return g._33Across.state.ivDone},ivReady:function(a,b){var c=!1,d;!this.ivDone()&&f.isArray(a.p)&&f.inArray(a.p,"sic_v1")&&a.sic.products&&
a.sic.products.inview&&(d=a.sic.products.inview.install_method||a.sic.install_method,"TI"==b.distro?"On Page"==d&&(c=!0):"On Page"!=d&&(c=!0));return c},ipReady:function(a){return a.sic.products&&a.sic.products.siab},ifReady:function(a){return a.sic.products&&a.sic.products.infeed}});Q.options={strictMode:!1,key:"source protocol authority userInfo user password host port relative path directory file query anchor".split(" "),q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,
loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};var p=e.body,w=e.documentElement,R=g.eval("/*@cc_on!@*/false"),ra=function(a,b){for(var c="",d=0;d<b;d++)c+=a;return c},C=ra("a",50),D=(Tynt.e||"")+"ic.tynt.com",Qa=(Tynt.e||"")+"cdn.tynt.com",ba=D+"/b/s",sa=(Tynt.e||"")+"platform.33across.com",q=function(a,b,c){a=e.createElement(a);f.extend(a,b);
f.extend(a.style,c);return a},x,E;g.addEventListener?(x=function(a,b,c){a.addEventListener(b,c,!1)},E=function(a,b,c){a.removeEventListener(b,c,!1)}):(x=function(a,b,c){a.attachEvent("on"+b,c)},E=function(a,b,c){a.detachEvent("on"+b,c)});var N=function(a,b){var c=g.location.hostname.split("."),d,k=2;do d=c.slice(c.length-k,c.length).join("."),d=a+";path=/;domain=."+d+";"+b,e.cookie=d,k++;while(-1==e.cookie.indexOf(a)&&k<=c.length);-1==e.cookie.indexOf(a)&&(e.cookie=a+";path=/;"+b)},ca=function(a){"complete"==
e.readyState?a():x(g,"load",function(b){setTimeout(function(){"undefined"!=typeof e.readyState||R||(e.readyState="complete");a()},10)})},t=function(a,b){var c=[],d=function(a,b){var c=n.protocol+a.replace("id="+C,"id="+f.tyntIds());-1<c.indexOf(D+"/b/p?")&&"string"==typeof Tynt.b&&(c+="&b="+Tynt.b);var d=new Image(1,1);b&&(d.onerror=b);d.src=c};t=function(a,b){c.push([a,b])};ca(function(){t=d;for(var a=0;a<c.length;a++)t(c[a][0],c[a][1]);c=null});t(a,b)},Ra=function(a){a=q("script",{async:"async",
src:n.protocol+a});var b=e.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},ta=function(a){var b=[],c="",d;for(d in a)a.hasOwnProperty(d)&&(b.push(c,d,"=",a[d]),c="&");return b.join("")},I=function(a){for(var b=0,c=100>a.length?a.length:100,d=0;d<c;d++)b+=a.charCodeAt(d);a=Math.floor(3844*Math.random());c=Math.abs(Date.now()-12281184E5);return ua(c,7)+ua((b+a)%3844,2)},va=function(a){if(62>a)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);var b=
Math.floor(a/62);a-=62*b;return 62<=b?va(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)},ua=function(a,b){var c=va(a);return ra("0",b-c.length)+c},S=function(a){return(a=f.trim(a))?a.split(/\s+/i).length:0},T=f.trim((e.title||g.location.hostname).toString()).replace(new RegExp(g.location.hash,"g"),""),wa=function(a){var b=
a.trace_type;delete a.trace_type;var c=a.g;delete a.g;for(var d=[],k="id wc f w h t c".split(" "),l=0;l<k.length;l++){var e=k[l],g=a[e];g&&d.push([e,encodeURIComponent(g).replace(/\'/g,"%27")]);delete a[e]}for(var f in a)a.hasOwnProperty(f)&&(k=a[f])&&d.push([f,encodeURIComponent(k).replace(/\'/g,"%27")]);a=[];var l=2048-((n.protocol+D+"/a/t/x#?").length+(3+c.length)+5),e=d.length,h=g=0,m=0,p,y,z,q,G=0;for(a[G]={g:c,tp:null};g<e&&35>a.length;)p=d[g][0],f=d[g][1],z=p.length+2,y=l-z-h,0<y?(k=f.substring(m,
m+y),q=k.slice(-2).indexOf("%"),-1<q&&(k=f.substring(m,m+y-2+q),h+=q+2),h+=k.length+z,m+=k.length,a[G][p]=k):h=l,h>=l&&(a[++G]={g:c,p:G},h=0),m>=f.length&&(g++,m=0);a[0].tp=a.length;t(D+"/b/t/"+b+"?"+ta(a[0]));for(c=1;c<a.length;c++)t(D+"/b/x/"+b+"?"+ta(a[c]))},da=function(){var a=[];return function(b){for(var c=a.length-1;0<=c;c--)if(a[c]==b)return!1;a.unshift(b);3<a.length&&a.pop();return!0}},Sa=da(),Ta=da(),Ua=function(a){var b,c=function(a){g.removeEventListener("blur",c,!1);ea(b);return!0};return function(a){b=
a.target||a.srcElement;g.removeEventListener("blur",c,!1);"IMG"==b.nodeName&&"A"!=b.parentNode.nodeName&&(g.addEventListener("blur",c,!1),setTimeout(function(){e.removeEventListener("blur",c,!1)},1E4));return!0}}(),xa=function(a){ea(a.target||a.srcElement,!0)},U,ya=function(a){a=a.target||a.srcElement;U="IMG"==a.nodeName?a:null},fa=function(a){var b=function(a){return"number"==typeof a.pageX?{x:a.pageX-(w.scrollLeft?w.scrollLeft:p.scrollLeft),y:a.pageY-(w.scrollTop?w.scrollTop:p.scrollTop)}:{x:a.clientX,
y:a.clientY}},c=function(a){a=b(a);return 0>=a.x||0>=a.y||a.x>=p.clientWidth||a.y>=p.clientHeight},d=function(a){a=b(a);return 0>=a.x||0>=a.y||a.x>=w.clientWidth||a.y>=w.clientHeight},k=function(a){return"#document"==a.target.nodeName},l=function(a){a=b(a);return 4>=a.x||4>=a.y||a.x>=w.clientWidth-4||a.y>=w.clientHeight-4},g=function(a){g=navigator.userAgent.match("MSIE")?e.compatMode&&-1!=e.compatMode.indexOf("CSS")?d:c:navigator.userAgent.match("Firefox")?k:l;g(a)};return function(a){U&&g(a)&&(ea(U),
U=null);return!0}}(),za=function(){return/tracer=test|tracer=no_tracing|disableTracer=/.test(g.location.href)||/disableTracer=y/.test(e.cookie)},Aa=function(){if(e.referrer){var a=g.location.hostname;return Q(e.referrer).host===Q(a).host}return!1};Tynt.ci=function(){var a;return function(b,c){a=c||a;var d=ba+["?ci=",b,"&id=",C,"&g=",a,"&r=",encodeURIComponent(e.referrer),"&ts=",Date.now()].join("");t(d)}}();Tynt.st=function(){var a;return function(b,c,d,k){a=d||a;b=[ba,"?",encodeURIComponent(b),"=",
encodeURIComponent(c),"&id=",C,"&g=",a,"&r=",encodeURIComponent(e.referrer),"&href=",encodeURIComponent(g.location.href),"&ts=",Date.now()];c="";if(k){c=[];d="";for(var l in k)k.hasOwnProperty(l)&&(c.push(d,encodeURIComponent(l),"=",encodeURIComponent(k[l])),d="&");c="&"+c.join("")}t(b.join("")+c)}}();var ga;Tynt.c?ga=function(){}:(Tynt.c=!0,Tynt.m=Tynt.m||[],Tynt.n=Tynt.n||[],ga=function(){var a=!0,b,c=function(b,c){var l={id:C,wc:S(c),c:c,f:a?1:0,t:T};f.extend(l,b);a=!1;wa(l)};g.addEventListener?
(navigator.userAgent.match(/Firefox\/2\b/)||p.addEventListener("copy",xa,!1),g.addEventListener("mousedown",ya,!1),g.addEventListener("dragleave",fa,!1),g.addEventListener("dragexit",fa,!1),e.addEventListener("contextmenu",Ua,!1)):(p.attachEvent("oncopy",xa),e.getElementsByTagName("html")[0].attachEvent("ondragleave",fa),p.attachEvent("onmousedown",ya));-1!==e.cookie.indexOf("tracertraffic=")&&(e.referrer&&-1!=e.referrer.indexOf(g.location.host)||N("tracertraffic=0","expires=Thu, 01 Jan 1970 00:00:00 GMT"));
f.callIc();f.callDeb();return function(a,k){if(!e.getElementById("tyntSh")){var l,h,m;k&&(e.selection&&e.selection.createRange?(h=e.selection.createRange(),m=h.duplicate(),l=h.text):(h=g.getSelection(),m=0<h.rangeCount&&h.getRangeAt(0),l=h.toString()));var p=a.src;if(p&&!l&&Ta(p)){h={trace_type:3,g:I(p),w:a.width,h:a.height};for(m=0;m<Tynt.n.length;m++)Tynt.n[m](h,p);c(h,p)}else if(l&&f.trim(l).length&&"TEXTAREA"!=a.nodeName&&"INPUT"!=a.nodeName){p=Sa(l);h={trace_type:1};p&&(b=I(l));h.g=b;for(var n=
!0,q=0;q<Tynt.m.length;q++)n=n&&Tynt.m[q](h,l,m,p);p&&n&&c(h,l)}}}});var V=function(a){a=a.charCodeAt(0);return 3584<=a&&3711>=a||11904<=a&&12591>=a||12688<=a&&40959>=a||63744<=a&&64255>=a||65072<=a&&65103>=a||131072<=a&&173791>=a||194560<=a&&195103>=a},Ba=function(a){a=a.getElementsByTagName("script");for(var b=a.length-1;0<=b;b--){var c=a[b];c.parentNode.removeChild(c)}},J=function(a,b){var c=f.docUrl(),c=c&&!1!==h.c?c:g.location.href,c=c.replace(/#(i|a)xzz=?(.*)$/g,""),c=c+"#"+("ixzz"+a);b&&(c+=
"&"+b);return c},ha=function(a){return a.replace(/^\s+|\s+$/g,"")},ia=e.defaultView,ja=R?!e.compatMode||-1==e.compatMode.indexOf("CSS"):!1,Va=R?!("XMLHttpRequest"in g):!1,ka=function(a){ka="undefined"!=typeof ia&&"undefined"!=typeof ia.getComputedStyle?function(a){return ia.getComputedStyle(a,"")}:function(a){return a.currentStyle};return ka(a)},Wa={t:3,p:6,w:7,f:8,i:9,l:10,g:11,ssbt:12,ssbf:13,ssbp:14,ssbl:15,ssbg:16},Ca=function(a){var b=new Date(Date.now()+864E5);N("tracertraffic="+a.toString(),
"expires="+b.toUTCString())},Xa=function(){if(Tynt.v)return!1;Tynt.v=!0;var a=g.location.href.match(/ixzz=?([^?&$#]*)/);if((a=(a&&2==a.length?a[1]:null)||Tynt.h)&&!Aa()){var b;(b=g.location.href.match(/ixzz=?([^?$#]*)/))?(b=b[1].match(/&([^?$]*)/),b=Tynt.k?Tynt.k.charAt(1):b&&b[1]?b[1]:null):b=null;a=D+"/b/v"+["?g=",a,/\?trace_owner_view/.test(g.location.href)?"&o=y":"","&id=",C,b?"&s="+b:"","&r=",encodeURIComponent(e.referrer),"&ts=",Date.now()].join("");t(a);Ca(Wa[b]||1);return!0}return!1},H=n.protocol+
(Tynt.e||"")+"cdn.tynt.com/images/ss/",Ya=n.protocol+"cdn.tynt.com/close.html",Da="undefined"!==typeof createImageMeme,Za=/Mobile|iP(hone|od|ad)|Android|BlackBerry|Tablet|IEMobile|Kindle|NetFront|Silk-Accelerated|(hpw|web)OS|Fennec|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Dolphin|Skyfire|Zune/,A=A||"",A=A+["#tyntSh div,#tyntSh span,#tyntSh img,#tyntSh a,div#tyntSh{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline;line-height:1;background:0;text-align:left}#tyntSh img,#tyntSh span{display:inline}#tyntSh div,div#tyntSh{display:block}div#tyntSh{z-index:9999999;position:absolute;height:62px;margin:10px;overflow:visible;background:#FFF;border-radius:5px;text-align:center;box-shadow: 0 2px 6px rgba(0,0,0,0.5)}div#tyntShTr{margin:-11px auto 0 auto;width:0;height:0;border-left:10px solid transparent;border-right:10px solid transparent;border-bottom:11px solid #F1F1F1}img#tyntShTw,img#tyntShP,img#tyntShFb,img#tyntShLi,img#tyntShGp{cursor:pointer;height:28px;width:28px;margin:3px 3px 2px 3px;vertical-align:bottom}div#tyntShPTL,div#tyntShHFL{color:#888;text-decoration:none;margin:0 0 2px 0;background-color:#F1F1F1;padding:2px 4px;border-radius:5px 5px 0 0}div#tyntShHFL{text-align:right;border-radius:0 0 5px 5px;margin:2px 0 0 0}div#tyntShHFL,span#tyntShHFLs,div#tyntShPTL{font:normal 8px Arial}",
"span#tyntShHFLs{cursor:pointer;"+(ja?"text-decoration:underline":"")+"}","span#tyntShHFLs:hover{color:#555;text-decoration:underline}div#tyntShCB{position:absolute;cursor:pointer;width:14px;height:14px;top:0;right:0;background-position:0 -14px;background-repeat:no-repeat}div#tyntShCB:hover{background-position: 0 0}"].join(""),v=function(){var a,b;return function(c,d,k){a=d||a;b=k||b;c=ba+["?w=",c,"&id=",C,"&g=",a,"&wc=",b,"&r=",encodeURIComponent(e.referrer),"&ts=",Date.now()].join("");t(c)}}(),
W=function(){return Za.test(navigator.userAgent||navigator.vendor||g.opera)},K=function(a){return-1<(h.ss||"").indexOf(a)},Ea=function(){return(h.ss||"").replace("p","").replace("m","").length},X=function(a,b){return b.length>a?b.slice(0,a-1)+"\u2026":b},$a=function(a,b,c){"undefined"===typeof c&&(c="w");b=J(b,c);return b=X(114,a)+" "+b},m={words:0,_content:"",guid:null,isBar:function(a){return!!(a||"").toString().match(/ssb/)},getContentFor:function(a){return m.isBar(a)?"":m._content},setContent:function(a){m._content=
a},getGuid:function(){return this.guid?this.guid:I(g.location.toString())},twitter:function(a,b,c){return q("img",{src:H+"t.png",title:"tweet this",id:a,onclick:function(a){g.open(n.protocol+"twitter.com/home?status="+encodeURIComponent($a(m.getContentFor(c),m.getGuid(),c)),"tweet","width=723,height=251");v(b,m.getGuid(),m.words)}})},facebook:function(a,b,c){return q("img",{src:H+"fb.png",title:"share on Facebook",id:a,onclick:function(a){a=["https://www.facebook.com/dialog/feed?app_id=158472647611546&link=",
encodeURIComponent(J(m.getGuid(),c)),"&description=",encodeURIComponent(X(140,m.getContentFor(c))),"&redirect_uri=",encodeURIComponent(Ya)].join("");g.open(a,"fbshare","width=985,height=450");v(b,m.getGuid(),m.words)}})},linkedin:function(a,b,c){return q("img",{src:H+"li.png",title:"share on LinkedIn",id:a,onclick:function(a){a=[n.protocol+"www.linkedin.com/shareArticle?mini=true","&url=",encodeURIComponent(J(m.getGuid(),c)),"&title=",T];m.getContentFor(c)&&(a.push("&summary="),a.push(encodeURIComponent(X(255,
m.getContentFor(c)))));a=a.join("");g.open(a,"lishare","width=520,height=450");v(b,m.getGuid(),m.words)}})},googleplus:function(a,b,c){return q("img",{src:H+"gp.png",title:"share on Google+",id:a,onclick:function(a){a=["https://plus.google.com/share?url=",encodeURIComponent(J(m.getGuid(),c))].join("");g.open(a,"gpshare","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600");v(b,m.getGuid(),m.words)}})},pinterest:function(a,b,c){}},la=function(a,b,c){var d=a.createElement("style");
d.id=b;d.type="text/css";b=a.createTextNode(c);d.styleSheet?d.styleSheet.cssText=b.nodeValue:d.appendChild(b);a.getElementsByTagName("head")[0].appendChild(d)},Fa=function(a,b,c){var d,k=function(a,b,c){m.guid=b;m.setContent(a);m.words=S(a);if(!(e.getElementById("tyntSh")||8>m.words)){v(0,m.guid,m.words);var k;if(e.selection&&e.selection.createRange){c=e.selection.createRange();var h=ja?"offset":"bounding";k=[];k[0]=c[h+"Left"]+(w.scrollLeft||p.scrollLeft);k[1]=c[h+"Top"]+(w.scrollTop||p.scrollTop);
k[2]=c.boundingHeight}else{a=q("span",{},{display:"inline"});b=c.startContainer;var f=c.endContainer,n=c.endOffset;try{h=e.createRange();h.setStart(f,n);h.setEnd(f,n);h.surroundContents(a);var y,z,t,G,r,u,n={top:0,left:0,bottom:0},F=a&&a.ownerDocument;F?(r=F.documentElement,"undefined"!==typeof a.getBoundingClientRect&&(n=a.getBoundingClientRect()),u="scrollTo"in F&&F.document?F:9===F.nodeType?F.defaultView||F.parentWindow:!1,y=n.top,z=n.left,t=n.right-n.left,G=n.bottom-n.top,"fixed"!=ka(a).position&&
(y+=u.pageYOffset||r.scrollTop||0,z+=u.pageXOffset||r.scrollLeft||0),y+=r.clientTop||0,z+=r.clientLeft||0,k=[z,y,t,G]):k=null;k[2]=a.offsetHeight;a.parentNode.removeChild(a);h.detach();b.parentNode.normalize();f.parentNode.normalize()}catch(A){}"undefined"!=typeof g.getSelection().setBaseAndExtent&&g.getSelection().setBaseAndExtent(c.startContainer,c.startOffset,c.endContainer,c.endOffset)}d.style.left=k[0]+"px";d.style.top=Math.max(k[1]+k[2],3)+"px";p.insertBefore(d,p.firstChild);x(p,"mousedown",
L);x(p,"touchstart",L)}};(function(){e.getElementById("tyntShCSS")||la(e,"tyntShCSS",A);d=q("div",{id:"tyntSh"},{width:Math.max(80,34*Ea())+"px"});ja||d.appendChild(q("div",{id:"tyntShTr"}));var a=q("div",{id:"tyntShPTL",innerHTML:"Powered by Tynt"});d.appendChild(a);a=q("div",{id:"tyntShHFL"});a.appendChild(q("span",{id:"tyntShHFLs",innerHTML:"Don't show again",onclick:ab}));var b=q("div",{id:"tyntShCB",title:"close",onclick:bb},{backgroundImage:"url("+(H+"x.png")+")"});K("f")&&d.appendChild(m.facebook("tyntShFb",
4,"f"));K("t")&&d.appendChild(m.twitter("tyntShTw",3,"w"));K("l")&&d.appendChild(m.linkedin("tyntShLi",8,"l"));K("g")&&d.appendChild(m.googleplus("tyntShGp",9,"g"));if(Da){var c=q("img",{src:H+"pi.png",title:"pin it",id:"tyntShP",onclick:function(){createImageMeme(void 0,void 0)}});Da&&d.appendChild(c)}W()||d.appendChild(a);d.appendChild(b)})();k(a,b,c);Fa=k},bb=function(a){L();v(2)},L=function(a){var b=e.getElementById("tyntSh"),c=a?a.target||a.srcElement:{id:""};!b||-1<c.id.indexOf("tyntSh")||(E(p,
"mousedown",L),E(p,"touchstart",L),p.removeChild(b),a&&v(1))},ab=function(a){L();a=new Date(Date.now()+31536E7);N("TyntSpeedShareHide=true","expires="+a.toUTCString());v(5)},Y=function(){return!Va&&-1==e.cookie.indexOf("TyntSpeedShareHide=true")},cb=function(a,b,c){Ea()&&setTimeout(function(){Y()&&Fa(b,a.g,c)},1);return!0};if("undefined"===typeof h)var h;r.afterDynamicConfigAndDocumentLoaded.push(function(a){if(a&&a.ssb){la(e,"tyntSbCSS",".tynt-speedshare-bar img{margin:0 3px;}");var b;var c=e;b=
ha("tynt-speedshare-bar");if(c.getElementsByClassName)b=c.getElementsByClassName(b);else if(c.querySelectorAll)b=c.querySelectorAll("."+b);else{for(var c=c.getElementsByTagName("*"),d=[],k=0;k<c.length;k++)c[k].className.match(b)&&d.push(c[k]);b=d}d=!1;for(k=0;k<b.length;k++)c=b[k],-1<a.ssb.indexOf("f")&&(c.appendChild(m.facebook("tyntSbFb",16,"ssbf")),d=!0),-1<a.ssb.indexOf("t")&&(c.appendChild(m.twitter("tyntSbTw",17,"ssbt")),d=!0),-1<a.ssb.indexOf("l")&&(c.appendChild(m.linkedin("tyntSbLi",19,
"ssbl")),d=!0),-1<a.ssb.indexOf("g")&&(c.appendChild(m.googleplus("tyntSbGp",20,"ssbg")),d=!0);d?v(14):v(15)}});var Z=[],O=[],Ga=[{x:970,y:250},{x:300,y:600},{x:300,y:1050},{x:970,y:90},{x:300,y:250},{x:970,y:250},{x:970,y:90},{x:180,y:150},{x:160,y:600},{x:728,y:90},{x:120,y:60},{x:88,y:31}],Ha=[/:\/\/[^\/]*?outbrain\.com/,/:\/\/ads\.yldmgrimg\.net/,/:\/\/[^\/]*?cdn\.adblade\.com/,/:\/\/[^\/]*?googlesyndication\.com/],A=A||"",A=A+["div.tyntShIh,.tyntShIh div,.tyntShIh span{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline;line-height:1;background:0;text-align:left}.tyntShIh img,.tyntShIh span{display:inline}.tyntShIh div,div.tyntShIh{display:block;outline:0}",
"div.tyntShIh{position:absolute;cursor:default;background:transparent url("+(H+"pi.png")+") no-repeat;width:43px;height:21px;opacity:0;filter:alpha(opacity=0);z-index:9999999;-webkit-transition:opacity 0.5s;-moz-transition:opacity 0.5s}","div.tyntIhHover{opacity:1;filter:alpha(opacity=100);cursor:pointer}"].join(""),db=function(a){a.getElementById("tyntShCSS")||la(a,"tyntShCSS",A)},eb=function(a){return n.protocol+"pinterest.com/pin/create/button/?url="+encodeURIComponent(J(I(a.src),"i"))+"&media="+
a.src+"&description="+encodeURIComponent(X(500,ha(a.title||a.alt)))},fb=function(a){if(h&&"undefined"!==typeof h.sspe){0===O.length&&(O=h.sspe.split(","));if(O.length!==Z.length)for(var b=0;b<O.length;b+=1)Z.push(new RegExp(O[b]));for(b=0;b<Z.length;b+=1)if(a.getAttribute("src")&&Z[b].test(a.getAttribute("src")))return!0}return!1},gb=function(a){var b,c;for(b=0;b<Ha.length;b++)if(Ha[b].test(a.src))return!0;for(b=0;b<Ga.length;b++)if(c=Ga[b],a.width===c.x&&a.height===c.y)return!0;return!1},hb=function(){if(!za()&&
Y()&&K("p")){var a=function(b){var c=b.document,d=null,k,e=null,f,m,n,p;k=c.createElement("div");k.className="tyntShIh";c.body.appendChild(k);x(k,"click",function(){"tyntShIh tyntIhHover"==k.className&&Y()&&(g.open(eb(e)),v(7))});db(c);x(c,"mouseover",function(a){a||(a=b.event);a=b.event?a.srcElement:a.target;!("IMG"===a.nodeName&&80<=a.height&&80<=a.width&&0!==a.src.indexOf("data:"))||gb(a)||fb(a)||"nopin"===a.getAttribute("nopin")||"nopin"===a.nopin||a===e&&k.showing||(null!==e&&e!==a&&q(),e=a,
e.__tyntPinItShow=!0,null!==d&&clearTimeout(d),d=setTimeout(function(){if(e.__tyntPinItShow&&Y()){var a=e,c=b.document,d=a.getBoundingClientRect(),g=(d.right+d.left+a.width)/2,h=(d.top+d.bottom+a.height)/2;a:{var f={};for(f.x=g;f.x>d.left;f.x-=20)for(f.y=h;f.y>d.top;f.y-=20)if(c.elementFromPoint(f.x,f.y)===a){d=f;break a}f.x=-1;f.y=-1;d=f}for(;d.y<=h&&c.elementFromPoint(d.x,d.y)===a;)d.y++;for(d.y--;d.x<=g&&c.elementFromPoint(d.x,d.y)===a;)d.x++;d.x--;a=b.document.documentElement;d={x:d.x+((b.pageXOffset||
a.scrollLeft||0)+(a.clientLeft||0)),y:d.y+((b.pageYOffset||a.scrollTop||0)+(a.clientTop||0))};k.style.left=d.x-45+"px";k.style.top=d.y-22+"px";k.className="tyntShIh tyntIhHover";k.showing=!0;e.__tyntPinItRecorded||v(6);e.__tyntPinItRecorded=!0}},"undefined"!==typeof h&&"undefined"!==typeof h.pt&&"i"==h.pt?0:1E3),x(c,"mousemove",p))});p=function(a){a=c.elementFromPoint(a.clientX,a.clientY);a!=e&&a!=k&&q()&&E(c,"mousemove",p)};var q=function(){return k.showing?(e.__tyntPinItShow=!1,k.showing=!1,k.className=
"tyntShIh",setTimeout(function(){k.style.left="-100px"},600),!0):!1};f=c.getElementsByTagName("iframe");for(n=f.length-1;0<=n;n--){m=f[n];try{m.src&&0!==m.src.indexOf(g.location.protocol+"//"+g.location.hostname)||"nopin"===m.getAttribute("nopin")||"nopin"===m.nopin||a(m.contentWindow)}catch(r){g.console&&Tynt.debug&&console.log("Bad iframe access",r,m)}}};a(g)}},Ia={vl:function(){Tynt.vl&&Tynt.vl.init()},track_selections:function(){var a=da();x(e,"mouseup",function(b){b="";e.selection&&e.selection.createRange?
(selection=e.selection.createRange(),b=selection.text):b=g.getSelection().toString();b=f.trim(b);b.length&&a(b)&&(b={id:C,g:I(b),wc:S(b),c:b.slice(0,2E3),t:T,trace_type:2},wa(b))})},track_attribution_views:function(){trackAttributionView=!0},sic_v1:function(){Tynt.ads.display("","","inview","TI")}};r.afterDynamicConfig.push(function(){var a,b,c=h.p;h.apollo&&(f.log("Injecting Apollo"),f.injectApolloScript());if(c)for(a=0;a<c.length;a++)if((b=c[a])&&"function"===typeof Ia[b])Ia[b]();else f.log('ERROR: Unknown module: "'+
b+'"');"function"===typeof u&&u("afterCheckModules")});var ib=sa+"/ipb.js",ma=function(){return-1!==e.cookie.indexOf("ty_attributionBlockedByIp=t")?!0:!1},Ja,jb=function(){Ja=setTimeout(function(){u("afterIpBlockCheck",h)},3E3);Ra(ib)};Tynt.ipb=function(a){clearTimeout(Ja);var b=!1;if("[object Array]"===Object.prototype.toString.apply(h.ipb)){for(var c=0;c<h.ipb.length;c++)if(a===h.ipb[c]){b=!0;break}a=b;b=new Date;b.setHours(b.getHours()+1);b="expires="+b.toGMTString();N("ty_attributionBlockedByIp="+
(!0===a?"t":"f"),b)}u("afterIpBlockCheck",h)};var Ka=(Tynt.e||"")+"ec.tynt.com",kb=";Attribution;Attribution Share Alike;Attribution No Derivatives;Attribution Non-Commercial;Attribution Non-Commercial Share Alike;Attribution Non-Commercial No Derivatives".split(";"),lb=" creativecommons.org/licenses/by/3.0 creativecommons.org/licenses/by-sa/3.0 creativecommons.org/licenses/by-nd/3.0 creativecommons.org/licenses/by-nc/3.0 creativecommons.org/licenses/by-nc-sa/3.0 creativecommons.org/licenses/by-nc-nd/3.0".split(" "),
aa=null,mb=function(a){return(a=a.match(/axzz([^?$]*)/))&&2==a.length?a[1]:null},nb=function(a){t(D+"/b/a?g="+a+"&id="+C+"&r="+encodeURIComponent(e.referrer)+"&ts="+Date.now(),function(a){})},La=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},ob=function(){var a;aa=!1;if("function"===typeof g.getSelection&&"function"===typeof e.createRange){var b=g.getSelection();if("function"===typeof b.addRange&&"function"===typeof b.removeAllRanges&&"number"===typeof b.rangeCount){var c=
[];for(a=0;a<b.rangeCount;a++)c.push(b.getRangeAt(a));a=e.body.appendChild(e.createElement("div"));a.contentEditable="false";var d=a.appendChild(e.createTextNode("\u00a0\u00a0\u00a0")),k=e.createRange(),f=k.cloneRange();k.setStart(d,0);f.setEnd(d,3);f.setStart(d,2);b.removeAllRanges();b.addRange(k);try{b.addRange(f)}catch(h){}aa=2==b.rangeCount;e.body.removeChild(a);b.removeAllRanges();k.detach();f.detach();for(a=0;a<c.length;a++)b.addRange(c[a])}}},P=!1,pb=function(a){var b,c="";null===aa&&ob();
if(P)return!1;P=!0;var d="";if(h.a){var k=J(a);"undefined"!==typeof trackAttributionView&&(c='<img src="'+n.protocol+D+"/b/l?id="+f.tyntIds()+"&g="+a+'">');a=c+'<a style="color: #003399;" href="';d+=h.ap+" ";h.st&&(d=d+a+k+'">'+La(T)+"</a> ");h.su&&(d=d+a+k+'">'+La(k)+"</a>");0<h.as.length&&(d=d+"\n<br>"+h.as+" ");0<h.cc&&(d=d+"\n<br>Under Creative Commons License: "+a+n.protocol+lb[h.cc]+'">'+kb[h.cc]+"</a>");if(h.w||h.f)d+="\n<br>Follow us: ",h.w&&(d=d+'<a href="'+n.protocol+Ka+"/b/rw?id="+f.tyntIds()+
"&u="+h.w+'" target="_blank">@'+h.w+" on Twitter</a>"),h.w&&h.f&&(d+=" | "),h.f&&(d=d+'<a href="'+n.protocol+Ka+"/b/rf?id="+f.tyntIds()+"&u="+h.f+'" target="_blank">'+h.f+" on Facebook</a>")}h.el&&(0<d.length&&(d+="\n<br>"),d+=h.el);var l,m;l=q("div",{},{overflow:"hidden",color:"#000000",backgroundColor:"#FFFFFF",textAlign:"left",textDecoration:"none",border:"none"});if(e.selection&&e.selection.createRange){var r=w.scrollLeft||p.scrollLeft,t=w.scrollTop||p.scrollTop;m=q("div",{},{overflow:"hidden",
position:"absolute",left:r+20+"px",top:t+20+"px",width:"1px",height:"1px"});p.insertBefore(m,p.firstChild);var u=e.selection.createRange();l.innerHTML=h.t?d+"<br><br>"+u.htmlText:u.htmlText+"<br><br>"+d;Ba(l);m.appendChild(e.createElement("br"));m.appendChild(l);d=p.createTextRange();d.moveToElementText(l);d.select();setTimeout(function(){p.removeChild(m);""!==u.text&&(u.select(),w.scrollLeft=r,p.scrollLeft=r,w.scrollTop=t,p.scrollTop=t);P=!1},0)}else if(aa)b=g.getSelection(),m=q("div",{},{height:0,
position:"absolute",top:"-1000px"}),m.innerHTML="<br>",h.t?(p.insertBefore(m,p.firstChild),l.innerHTML=d+"<br><br>"):(p.appendChild(m),l.innerHTML="<br>"+d+"<br>"),m.appendChild(l),d=e.createRange(),d.selectNode(l),b.addRange(d),g.setTimeout(function(){m.parentNode.removeChild(m);P=!1},0);else{b=g.getSelection();var v=b.getRangeAt(0),d=q("span",{innerHTML:d});h.t?(d.innerHTML+="<br/><br/>",l.appendChild(d),l.appendChild(v.cloneContents())):(l.appendChild(v.cloneContents()),d.innerHTML="<br/><br/>"+
d.innerHTML,l.appendChild(d));Ba(l);l.style.width=.1;l.style.height=.1;l.style.position="absolute";l.style.top="-1000px";l.style.left="-1001px";l.appendChild(e.createElement("br"));d=l.innerText.length;p.insertBefore(l,p.firstChild);l.innerText.length!=d&&(l.style.overflow="");b.selectAllChildren(l);setTimeout(function(){l.parentNode.removeChild(l);b.removeAllRanges();b.addRange(v);P=!1},0)}return!0},rb=function(a,b,c){c=!0;if(h.a||h.el){var d;d=ha(b);d=2<=d.length?V(d.charAt(0))||V(d.charAt(d.length-
1))||V(d.charAt(d.length/2)):V(d);var e;if(e=h.h)a:{e=(e=qb())?e.className.split(/\s+/):[];for(var f=e.length-1;0<=f;f--)if(void 0!==h.h[e[f]]){e=h.h[e[f]];break a}e=void 0}if(!1!==e&&(d&&b.replace(/\s/g,"").length>=2*h.aw||!d&&S(b)>=h.aw)||e)if(h.a||h.el)c=pb(a.g),h.a&&(a.trace_type=0)}return c},qb=function(){return e.selection&&e.selection.createRange?function(){var a=e.selection.createRange(),b=a.duplicate();b.collapse(!0);return(b=b.parentElement())&&f.trim(a.text)==f.trim(b.innerText)?b:null}:
function(){var a=g.getSelection().getRangeAt(0),b=3==a.startContainer.nodeType?a.startContainer.parentNode:a.startContainer;return b&&f.trim(a.toString())==f.trim(b.textContent)?b:null}}(),sb=function(a){var b=a?864E5:-5E3,b=new Date(Date.now()+b);e.cookie="tracerabg="+a+";path=/;expires="+b.toUTCString()},ub=function(a){var b;a:{b=e.getElementsByTagName("script");for(var c=0;c<b.length;c++)if(/\/show_afs_search\.js/i.test(b[c].src)){b=!0;break a}b=!1}!b&&tb(g.location)&&(Tynt.b=a||I(g.location.href),
g.location.replace(g.location.href+("#"===g.location.href[g.location.href.length-1]?"":"#")+"axzz"+Tynt.b))},tb=function(a){if(""!==a.hash&&"#"!==a.hash)return!1;if("boolean"==typeof h.ba&&h.ba)h.ba=["/"];else if(!h.ba)return!0;for(var b,c=h.ba.length-1;0<=c;c--){b=null;var d=h.ba[c],e=d.indexOf("/");0!==e&&(b=d.slice(0,e),d=d.slice(e));if(!b||a.host==b)if("#"==d.charAt(d.length-1)){if(0===a.pathname.indexOf(d.slice(0,-1)))return!1}else if(a.pathname==d)return!1}return!0},vb=function(){e.cookie.match(/ty_attributionBlockedByIp=[tf]/)||
"[object Array]"!==Object.prototype.toString.apply(h.ipb)?u("afterIpBlockCheck",h):jb();0!==Tynt.settings._error||ma()||Tynt.m.push(rb);if(h.b&&!ma()){var a=mb(g.location.href);a?"#axzz"+f.getCookie(e.cookie,"tracerabg")==g.location.hash||Aa()||(nb(a),Ca(2)):(ub(f.getCookie(e.cookie,"tracerabg")),sb(Tynt.b))}(/tynt-mobile-ss-test/.test(g.location.href)||h.ss&&(W()&&W()&&K("m")||!W()))&&!ma()&&(Tynt.m.push(cb),ca(hb));u("afterDynamicConfig",h);ca(function(){u("afterDynamicConfigAndDocumentLoaded",
h)})};Tynt.cmd.push(function(){h=Tynt.settings.get();vb()});var Ma=function(){var a=e.title.indexOf("#ixzz");-1<a&&(e.title=e.title.substring(0,a));a=e.title.indexOf("#axzz");-1<a&&(e.title=e.title.substring(0,a))},wb=function(){for(var a=0;a<Tynt.length;a++)if(Tynt[a]&&22==Tynt[a].length)return Tynt[a];return null},na=function(a){if(!a)return{};for(var b={},c=a.substring(a.indexOf("?")+1).split("&"),d=0;d<c.length;d++){var e=c[d].split("=");0===e[0].indexOf("amp;")&&(e[0]=e[0].substring(4));b[e[0]]=
e[1]}a=a.split("/");a.pop();b.scriptPathUri=a.join("/");return b}(function(){for(var a=e.getElementsByTagName("script"),b=0;b<a.length;b++)if(/\/tracer.*\?/i.test(a[b].src))return a[b].src;return null}()),Na=na.user||wb();if(!Na)throw Error("Error finding Tynt Insight userId. Please check your HTML for errors.");na.user&&Tynt.push(na.user);/tracer=test/.test(g.location.href)&&t(sa+"/script/verify/"+Na);(function(){if(/disableTracer=/.test(g.location.href)){var a=g.location.href.match(/disableTracer=([^?$]*)/)[1],
b=new Date;b.setDate(a&&"on"==a?b.getDate()+365:b.getDate()-2);N("disableTracer="+(a&&"on"==a?"y":"n"),"expires="+b.toUTCString());b=q("div",{id:"TyntLocalOptOut"},{zIndex:"10000",position:"absolute",top:"10%",left:"10%",width:"80%",height:"80%",backgroundColor:"white",color:"black",textAlign:"center",fontSize:"32px",paddingTop:"10%",border:"1px solid gray"});b.innerHTML="Tynt Insight has been turned "+(a&&"on"==a?"off":"on")+" in this browser.<br>You may close this window.";p.insertBefore(b,p.firstChild)}})();
if(!za()){R&&(Ma(),e.attachEvent("onpropertychange",Ma));var ea=ga();Xa();Tynt.settings.download()}if("undefined"===typeof Oa)var Oa=10;(new Date).getDate()===Oa&&function(){var a=e.createElement("script"),b=e.getElementsByTagName("script")[0];a.async="async";a.type="text/javascript";a.src=n.protocol+Qa+"/cb.js";b.parentNode.insertBefore(a,b)}();var oa=null,pa=0,qa=function(){"object"==typeof e.body.oncopy&&null!==e.body.oncopy?(e.body.oncopy=null,v(13)):setTimeout(qa,2E3)},xb=function(){"undefined"===
typeof stlib||"undefined"===typeof stlib.hash||"undefined"===typeof stlib.hash.doNotCopy||stlib.hash.doNotCopy||(qa(),setTimeout(function(){clearInterval(oa)},2E3));pa+=1;5<=pa&&clearInterval(oa)};r.afterDynamicConfigAndDocumentLoaded.push(function(){if("undefined"===typeof stlib||"undefined"===typeof stlib.hash||"undefined"===typeof stlib.hash.doNotCopy||stlib.hash.doNotCopy){for(var a=!1,b=e.getElementsByTagName("script"),c=0;c<b.length;c++)if(b[c].getAttribute("src")&&/sharethis/.test(b[c].src)){a=
!0;break}a&&(oa=setInterval(xb,2E3))}else qa();"function"===typeof u&&u("afterProtectTynt")});Tynt.vl||(Tynt.vl={apiKey:"284d869ffe43382ebe88a02cabb697ab",apiUrl:"vlr.tynt.com",enabled:!1,debug:!1,subId:"33Across",init:function(a){if(!this.enabled){x(e,"mousedown",this.onMousedown);x(g,"unload",this.onUnload);n.isSecure&&(this.apiUrl="redirect.viglink.com");0<g.location.search.indexOf("__tcvldebug=1")&&(this.debug=!0);this.debug&&x(e,"click",this.onClick);if(a)this.subId=a;else{a:{a=f.unique(Tynt);
for(var b=0;b<a.length;b++)if(22===a[b].length&&0>a[b].toString().indexOf("!")){a=a[b];break a}a=""}a&&(this.subId=a)}this.enabled=!0;f.log("vl.init 5.1"+(this.debug?" debug":""))}},aInit:function(){var a,b;for(a=0;a<Tynt.length;++a)if((b=Tynt[a])&&(0<=b.indexOf("w!")||0<=b.indexOf("wp!"))){this.init(b);break}},onMousedown:function(a){a=a||g.event;for(var b=a.target||a.srcElement;b&&"a"!=b.nodeName.toLowerCase();)b=b.parentNode;b&&((a=Tynt.vl.validate(b.getAttribute("href")))?(b.setAttribute("href",
Tynt.vl.buildUrl(b,a)),Tynt.vl.debug&&f.log("href changed to:",Tynt.vl.buildUrl(b,a))):Tynt.vl.debug&&f.log("href not modified:",b.getAttribute("href")))},onClick:function(a){Tynt.vl.pd(a||g.event)},validate:function(a){var b,c=null;a&&(a=f.trim(a),b=a.indexOf(g.location.hostname),0>a.indexOf(Tynt.vl.apiUrl)&&(0>b||8<b)&&(0==a.indexOf("//")?c=g.location.protocol+a:0==a.indexOf("http")&&(c=a)));return c},onUnload:function(){Tynt.vl.enabled&&(Tynt.vl.enabled=!1,E(e,"mousedown",Tynt.vl.onMousedown),
E(g,"unload",Tynt.vl.onUnload),Tynt.vl.debug&&E(e,"click",Tynt.vl.onClick))},buildUrl:function(a,b){return n.protocol+this.apiUrl+"/?format=txt&key="+this.apiKey+"&u="+encodeURIComponent(b)+"&subId="+this.subId+"&txt="+this.enc(a.textContent||a.innerText||"")+"&loc="+this.enc(g.location.href)+"&ref="+this.enc(e.referrer)+"&title="+this.enc(e.title)},enc:function(a){return encodeURIComponent(f.trunc(a,300))},pd:function(a){a.preventDefault?a.preventDefault():g.event&&(g.event.returnValue=!1)}})}else setTimeout(function(){Tynt.TIL()},
62)};Tynt.TIL()}();
