var MAX_20df53bc = '';
MAX_20df53bc += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
MAX_20df53bc += "/* openads=http://idli.inzanecenter.com/www/hercules bannerid=145 zoneid=20 source={obfs:} */\n";
MAX_20df53bc += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
MAX_20df53bc += "google_ad_client = \"pub-7359360881399793\";\n";
MAX_20df53bc += "/* 120x240, created 3/31/08 */\n";
MAX_20df53bc += "google_ad_slot = \"6904098046\";\n";
MAX_20df53bc += "google_ad_width = 120;\n";
MAX_20df53bc += "google_ad_height = 240;\n";
MAX_20df53bc += "//-->\n";
MAX_20df53bc += "<"+"/script>\n";
MAX_20df53bc += "<"+"script type=\"text/javascript\"\n";
MAX_20df53bc += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
MAX_20df53bc += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://idli.inzanecenter.com/www/hercules/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_145\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://idli.inzanecenter.com/www/hercules/woody.php?bannerid=145&amp;campaignid=124&amp;zoneid=20&amp;source={obfs:}&amp;channel_ids=,&amp;loc=http%3A%2F%2Fwww.pagalguy.com%2Fforum%2Fcat-and-related-discussion%2F3321-profile-people-who-have-converted-10.html&amp;referer=http%3A%2F%2Fwww.pagalguy.com%2Fforum%2Fcat-and-related-discussion%2F3321-profile-people-who-have-converted-9.html&amp;cb=aab3b32b4e\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
document.write(MAX_20df53bc);
