/*
 Quantcast measurement tag
 Copyright (c) 2008-2017, Quantcast Corp.
*/
window.__qc=function(b){if(b.__qc)return b.__qc;var C="a ce cm dst enc fpa fpan je ns ogl rf tzo sr".split(" "),n=b.document,z=b.navigator,E="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),I=!1,J=!1,F=0,g=[],t=[],v=[],e={tcYgbCswcTSeq:1,"01-0VIaSjnOLg":1,aD1qr93XuF6aC:1,"56WJ0KtIxWJ_2":1,T1nhLcmCjVzQS:1,zddNYNtUkUhdQ:1,"59TntzuqummDw":1,P7x87XHnVfbWr:1,HGAVM7nQJ_sep:1,
"w9vzus-GKCA0U":1,"00TsOkvHvnsZU":1,effSsmMYCbAck:1,PFW5FesqXn206:1,"0dYLvhSGGqUWo":1,c1rF4kxgLUzNc:1,"5brKQLtleyIQU":1,"mEzuYq24VEJ-3":1,"57OGVHgSOoedo":1,"e7wR0qsM6-pDa":1,"8tgFhCTDYhV2V":1,"82MbSinIaQJw2":1,buQ2dAnrdTGCS:1,"49SVsgIZlUqPk":1,eeFYJkotb1rUU:1,EzVU5HfAMVqEV:1,"45nh8QKbsf2Xk":1,sLJ2v5QaN4z2Y:1,"5cvC4NOeGmtNA":1,"573scDfDoUH6o":1,"915Y6SMHQQJHI":1,z0zMG4nCgXzzj:1,"124BfeS-bwiSE":1,"ZzStSGgW6hG-4":1,KUMT4fYgcdEeg:1,fug7wP0GuN1h6:1,cd12aNCzw_ZaB:1,"51zXP5Cc9sxvQ":1,"4dIM5nVs2rFio":1,"8fZNjMQsH1Ews":1,
C6W3aFrWFMS7m:1,N7ekbgK3G3jrt:1,dfQGRefil9mes:1,"9axVJDmh4EHIM":1,NPcfSf1E0V1T1:1,"72V4-XKpaKDrE":1,"8cV3w6ZJH0sXI":1,sHwqAaPHqVjee:1,b15U9CAASyBMc:1,"32B7jMG1UAajk":1},h=[],k={},p=0,f=[],m=null,Y={},w={},ja=null,r,Z=[].slice,ka,$,P,q,A,aa,Q,la,ma,na,K,ba,R,S,oa,pa,L,qa,ra,sa,ta,s,ua,D,va,T,wa,xa,ca,ya,za,da,B,Aa,M,Ba,U,Ca,Da,V,Ea,ea,fa,Fa,ga,G,W,N,O,ha,ia,X,u=function(a){try{return{init:S,hash:R,push:oa,rules:Ca,hasRules:V,defaults:Fa,__qc:function(){return!0}}[a].apply(null,Z.call(arguments,1))}catch(c){return!1}};
u.evts=0;u.v=2;u.SD=E;u.qpixelsent=[];U=function(a){var c=a?a.length||0:0,d;for(d=0;d<c;d++)if(!a[d])return!1;return!0};fa=function(a){(a=a||b._qacct)&&(da(h,a)||h.push(a))};da=function(a,c){var d=a.length,b;for(b=0;b<d;b++)if(a[b]===c)return!0;return!1};M=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};Ba=function(a){var c,d;c=M(a);if("array"===c)return a.slice(0);if("object"===c){c={};for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c}return"string"===c?""+a:a};
oa=function(a,c){s(a,c)};V=function(a){return da(v,a)};Fa=function(a,c){var d;a&&((d=Y[a])&&(c=O(c,d)),c.qacct&&delete c.qacct,Y[a]=c)};ga=function(a){var c,d;if(q(a))for(c in a)if("string"==typeof a[c]){c=a.event||"load";d=a.media||"webpage";"rule"!==c&&"load"!==c||"webpage"!==d&&"ad"!==d?s(a):(d=a.qacct||b._qacct,a.qacct=d,c=(c=w[d])?O(c,a):a,w[d]=c);fa(a.qacct);break}else"object"==typeof a[c]&&null!=a[c]&&ga(a[c])};O=function(a,c){var d={};d.qacct=a.qacct||c.qacct;d.event="load"===a.event||"load"===
c.event?"load":a.event&&c.event?a.event||c.event:null;d.media=null;d.media="webpage"===a.media||"webpage"===c.media?"webpage":"ad"===a.media||"ad"===c.media?"ad":a.media||c.media;ca(d,a,c);ca(d,c,a);d.event||delete d.event;d.media||delete d.media;return d};ca=function(a,c,d){var b,H,h,k,f,g;for(b in c)c.hasOwnProperty(b)&&!a.hasOwnProperty(b)&&(H=c[b],h=d[b],k="",f=!!H&&"string"==typeof H,g=!!h&&"string"==typeof h,f&&(k=H),f&&g&&(k+=","),g&&(k+=h),a[b]=k)};G=function(){var a=[],c,d;if(!(0<p)){Aa();
for(c in w)w.hasOwnProperty(c)&&w[c]&&(d=w[c],a.push(d),delete w[c]);1==a.length&&s(a[0]);1<a.length&&s(a)}};W=function(){var a=[],c,d,b;b=h.slice(0);for(c=0;c<b.length;c++)d=b[c],e.hasOwnProperty(d.substring(2))?k[d]=5:V(d)||a.push(d);if(0===a.length)G();else for(c=0;c<a.length;c++)d=a[c],v.push(d),ya(d)};za=function(){for(var a;f[0]&&("loaded"==f[0].readyState||"complete"==f[0].readyState);)a=f.shift(),a.onreadystatechange=null,m.parentNode.insertBefore(a,m),N()};ya=function(a){var c,d;c=("https:"===
n.location.protocol?"https://":"http://")+"rules.quantcount.com/rules-"+a+".js";m=m||n.scripts[0];p++;d=n.createElement("script");"async"in d?(d.src=c,d.async=!1,d.onload=function(){k[a]=0;N()},d.onerror=function(){k[a]=1;N()},m.parentNode.insertBefore(d,m)):d.readyState?(k[a]=2,f.push(d),d.onreadystatechange=za,d.src=c):(k[a]=4,N())};N=function(){p-=0<p?1:0;G()};Ca=function(){var a=!0,c,d,b;if(arguments.length){b=function(c){a?ga(c):s(c,!0)};for(c=0;c<arguments.length;c++)d=Z.call(arguments[c],0),
d.splice(1,0,b),Da.apply(null,d);a=!1;I&&G()}};Da=function(a,c){var d=[],b=[],H=c||s,h,f,g,e,p;if((h=Z.call(arguments,2))&&h.length){f=h[0]||U;g=h[1];e=h[2];h=e.length;for(p=0;p<h;p++)d.push(!1),b.push(null);d={p:a,f:d,r:f,c:e,a:g,v:b};V(a)||v.push(a);t.push(d);Ea(d,H)}else v.push(a),k[a]=6};Ea=function(a,c){var d=a?a.c?a.c.length:0:0,b;for(b=0;b<d;b++)(function(d){var b,h;try{b=a.c[d][0],h=a.c[d].slice(1),h.splice(0,0,function(b){a.f[d]=!0;a.v[d]=b;ea(a,c)}),b.apply(null,h)}catch(k){a.f[d]=!0,a.v[d]=
!1,ea(a,c)}})(b)};ea=function(a,c){var d=a.a,b=a.v,h=a.r||U,k,f,g,e,p,l;(k=U(a.f))&&(k=k&&h(b));if(k)for(b=0;b<d.length;b++)try{f=d[b][0];g=1<d[b].length?d[b].slice(1):[];g=g.concat(a.v);e=f.apply(null,g);p={qacct:a.p,event:"rule"};for(l in e)e.hasOwnProperty(l)&&"qacct"!==l&&(p[l]=e[l]);c(p)}catch(q){}};ka=function(){return $(0)!==$(6)?1:0};$=function(a){a=new Date(2E3,a,1,0,0,0,0);var c=a.toGMTString(),c=new Date(c.substring(0,c.lastIndexOf(" ")-1));return a-c};P=function(a){return a.replace(/\./g,
"%2E").replace(/,/g,"%2C")};A="function"===typeof encodeURIComponent?encodeURIComponent:P;q=function(a){return"undefined"!=typeof a&&null!=a};aa=function(){return Math.round(2147483647*Math.random())};Q=function(a){var c="",d=n.cookie,b;if(!d)return c;b=d.indexOf(a+"\x3d");a=b+a.length+1;-1<b&&(c=d.indexOf(";",a),0>c&&(c=d.length),c=d.substring(a,c));return c};la=function(){var a="",c=K(),b,h,k;if(1===F)return";fpan\x3du;fpa\x3d";b=R(c);for(h=0;h<E.length;h++)if(E[h]===b)return";fpan\x3du;fpa\x3d";
b=new Date;h=Q("__qca");if(0<h.length){try{k=+h.split("-")[2],338688E5<b-k&&(n.cookie=["__qca\x3d",h,"; expires\x3d",(new Date(k+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""))}catch(f){}a+=";fpan\x3d0;fpa\x3d"+h}0===Q("__qca").length&&(h="P0-"+aa()+"-"+b.getTime(),n.cookie=["__qca\x3d",h,"; expires\x3d",(new Date(b.getTime()+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""),h=Q("__qca"),a=0<h.length?a+(";fpan\x3d1;fpa\x3d"+h):a+";fpan\x3du;fpa\x3d");return a};ma=function(a){n.cookie=
a+"\x3d; expires\x3dThu, 01 Jan 1970 00:00:01 GMT; path\x3d/; domain\x3d"+K()};K=function(){var a,c,b,h;a=n.domain;"www."===a.substring(0,4)&&(a=a.substring(4,a.length));c=a.split(".");h=c.length;if(3>h)return a;b=c[h-1];return 3>b.length?a:a=c[h-2]+"."+b};ba=function(a,c){var b;for(b=0;b<c.length;b++)a^=c.charCodeAt(b),a+=(a<<1)+(a<<4)+(a<<7)+(a<<8)+(a<<24);return a};R=function(a){var c;c=ba(2166136261,a);a=ba(3386659096,a);return Math.round(Math.abs(c*a)/65536).toString(16)};wa=function(a){var c,
b;if(a&&"object"===M(a))for(b=0;b<C.length;b++)c=C[b],a.hasOwnProperty(c)&&a[c]&&delete a[c]};T=function(a,c,d){var h={},f=b._qacct,g=null,e="webpage",p="load",n={},m,l,f=c?c.qacct||b._qacct:b._qacct;m=w[f];c?m&&(c=O(c,m)):c=m;f&&delete w[f];wa(c);if(null!=c)for(l in c)n[l]=!0,c.hasOwnProperty(l)&&"string"===typeof l&&"string"===typeof c[l]&&("uid"===l||"uh"===l?(pa()||(g=R(c[l])),delete c[l]):"qacct"!==l&&(0<c[l].length?h[l+a]=A(c[l]):n[l]=!1,"media"===l&&(e=c[l]),"event"===l&&(p=c[l])));if("string"!==
typeof f){if(!q(b._qacct)||0===b._qacct.length)return null;f=b._qacct}if(f){if(m=Y[f])for(l in m)"string"===typeof l&&m.hasOwnProperty(l)&&!n[l]&&(h[l+a]=A(m[l]),"media"===l&&(e=m[l]),"event"===l&&(p=m[l]))}else return null;n=k[f];q(n)||(n=3);h["rf"+a]=""+n;"string"===typeof g&&(c.uh=g,h["uh"+a]=A(g));if("webpage"===e&&"load"===p){for(c=0;c<u.qpixelsent.length;c++)if(u.qpixelsent[c]===f&&!d)return null;u.qpixelsent.push(f)}"ad"===e&&(F=1);h["a"+a]=f;return h};va=function(a){var c=[],b;for(b in a)a[b]&&
a.hasOwnProperty(b)&&c.push(b+"\x3d"+a[b]);return c.join(";")};xa=function(){var a=n.getElementsByTagName("meta"),c="",b,h,f,k;for(b=0;b<a.length;b++){f=a[b];if(1E3<=c.length)return c;q(f)&&q(f.attributes)&&q(f.attributes.property)&&q(f.attributes.property.value)&&q(f.content)&&(h=f.attributes.property.value,f=f.content,3<h.length&&"og:"===h.substring(0,3)&&(0<c.length&&(c+=","),k=80<f.length?80:f.length,c+=P(h.substring(3,h.length))+"."+P(f.substring(0,k))))}return A(c)};na=function(a){return"object"===
typeof a?["p","approved"===a.consent?"a":"d","asserted"===a.source?"e":"i"].join(""):""};pa=function(){var a=!1;q(b.external)&&(a=b.external,a="function"===typeof a.InPrivateFilteringEnabled&&!0===a.InPrivateFilteringEnabled());return a||"1"==z.doNotTrack||"yes"===z.doNotTrack||"1"==z.msDoNotTrack};s=function(a,c){var d="function"===typeof encodeURIComponent?"n":"s",h=aa(),f="",k="",e="",p="",m="",t="u",l="1",s=[],x,y,r,v,w;F=0;q(u.qpixelsent)||(u.qpixelsent=[]);if(q(a))if(x=M(a),"object"===x)y=T("",
a,c);else{if("array"===x)for(x=0;x<a.length;x++)r=T("."+(x+1),a[x],c),y=0===x?r:O(y,r)}else"string"===typeof _qacct&&(y=T("",null,c));y&&(x=z.cookieEnabled?"1":"0","undefined"!=typeof z.javaEnabled&&(t=z.javaEnabled()?"1":"0"),q(b._qmeta)&&(k=";m\x3d"+A(b._qmeta),b._qmeta=null),self.screen&&(f=screen.width+"x"+screen.height+"x"+screen.colorDepth),r=new Date,v=ka(),w=la(),b.location&&b.location.href&&(e=A(b.location.href)),n&&n.referrer&&(m=A(n.referrer)),b.self===b.top&&(l="0"),y.url?p=e:y.url=e,
y.ref||(y.ref=m||""),e=xa(),m=va(y),s.push("/pixel;r\x3d"+h+";"+m+w+";ns\x3d"+l+";ce\x3d"+x),s.push((y.ref?"":";ref\x3d")+";je\x3d"+t+";sr\x3d"+f+";enc\x3d"+d+";dst\x3d"+v+";et\x3d"+r.getTime()+";tzo\x3d"+r.getTimezoneOffset()+(p?";ourl\x3d"+p:"")+k+";ogl\x3d"+e),g.push(s),D())};ua=function(a){var c=new Image;a=[b.location.protocol,"//pixel.",qa(r)?"quantserve.com":"quantcount.com",a[0],";cm\x3d",na(r),a[1]].join("");c.alt="";c.src=a;c.onload=function(){c&&"number"==typeof c.width&&3===c.width&&ma("__qca")}};
D=function(){if(r)for(;g.length;)ua(g.shift());else ta()};qa=function(a){return!0===a||1===a||1===a||q(a)&&"approved"===a.consent?!0:!1};ta=function(){if(!q(r)){if(b.top===b.self){if("object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi){ra("getConsent","advertising");return}}else if(b.postMessage&&"object"===typeof JSON){sa("getConsent","advertising");return}r=1}D()};ra=function(a,c){r=PrivacyManagerAPI.callApi(a,"quantserve.com",K(),"truste.com",c);D()};sa=function(a,
c){var d={PrivacyManagerAPI:{timestamp:(new Date).getTime(),action:a,self:"quantserve.com",domain:K(),authority:"truste.com",type:c}};if(b.addEventListener)b.addEventListener("message",L,!1);else if(b.attachEvent)b.attachEvent("onmessage",L);else{r=!0;D();return}try{b.top.postMessage(JSON.stringify(d),"*")}catch(h){}ja=setTimeout(function(){q(r)||(r=!0,D())},25)};L=function(a){var c=null;if(a.source===window.top){try{c="object"===typeof JSON&&JSON.parse(a.data)}catch(d){}c&&"object"===typeof c.PrivacyManagerAPI&&
(clearTimeout(ja),b.removeEventListener?window.removeEventListener("message",L,!1):b.detachEvent&&window.detachEvent("onmessage",L),r=c.PrivacyManagerAPI,D())}};ha=function(){var a=arguments,c,b;B([].slice.call(a));for(b=0;b<a.length;b++)c=a[b],s(c);h.length?W():G()};B=function(a){var c=M(a);if("array"===c)for(c=0;c<a.length;c++)B(a[c]);else"object"===c&&fa(a.qacct||b._qacct)};Aa=function(){var a;J||b._qevents.length||b.ezt.length||"undefined"===typeof _qacct||(s({qacct:b._qacct}),J=!0);if(!u.evts){for(a in b._qevents)b._qevents.hasOwnProperty(a)&&
s(b._qevents[a]);for(a in b.ezt)b.ezt.hasOwnProperty(a)&&s(b.ezt[a]);b._qevents={push:ha};b.ezt.push=function(){var a=arguments,d;if(q(b.queueManager))for(d=0;d<a.length;d++)b.queueManager.push(a[d]);else ha.apply(this,arguments)};u.evts=1}};X=function(a){var c;a&&(c=Ba(a),B(a),b._qevents.push(c))};ia=function(a){a.push=function(){B([].slice.call(arguments));W();return[].push.apply(a,arguments)}};S=function(){q(b._qevents)||(b._qevents=[]);q(b.ezt)||(b.ezt=[]);X(b._qoptions);X(b.qcdata);X(b.smarttagdata);
u.evts||(ia(b._qevents),ia(b.ezt));B(b.ezt);B(b._qevents);B({qacct:b._qacct});b._qoptions=null;h.length?W():G();I=!0};b.quantserve=b.quantserve||S;u.quantserve=S;return u}(window);
try{__qc("hasRules","p-0dUe_kJAjvkoY")||function(b,C,n){var z="twitter:title og:title title author authors article:author article:authors bt:author bt:authors sailthru.author sailthru.authors sailthru.title lv:author lv:authors lv:title".split(" "),E=function(b){return b.replace(/^[\s\ufeff\xA0]+|[\s\ufeff\xA0]+$/g,"")},I=function(b){return{}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase()},J=function(b,k,e){return b?"nc"===b?!k||!e||0>k.indexOf(e):"eq"===b?k===e:"sw"===b?0===k.indexOf(e):
"ew"===b?(b=k.length-e.length,k=k.lastIndexOf(e,b),-1!==k&&k===b):"c"===b?0<=k.indexOf(e):!1:!1},F=function(b){var k=n.createElement("a");k.href=b;return k},g=function(b,k,e){var f;f=C.top===C.self?n.location.href:F(n.referrer).href;J(k,f,e)?b(f):b(!1)},t=function(b,e,g){var f;f=C.top===C.self?n.location.pathname:F(n.referrer).pathname;J(e,f,g)?b(f):b(!1)},v=function(b){return{labels:b}},e=function(b){return"array"===I(b)?v(b.join(",")):v(""+b)};__qc.apply(null,["rules",[b,null,[[e,"Film-TV Adaptation.Outlander"]],
[[g,"c","book/show/10988.Drums_of_Autumn"]]],[b,null,[[e,"Film-TV Adaptation.Outlander"]],[[g,"c","book/show/10987.Voyager"]]],[b,null,[[e,"Film-TV Adaptation.Outlander"]],[[g,"c","book/show/5364.Dragonfly_in_Amber"]]],[b,null,[[e,"Film-TV Adaptation.Outlander"]],[[g,"c","/book/show/10964.Outlander"]]],[b,null,[[e,"Film-TV Adaptation.Outlander"]],[[g,"c","book/show/21532133-outlander"]]],[b,null,[[e,"Film-TV Adaptation.Outlander"]],[[g,"c","author/show/3617.Diana_Gabaldon"]]],[b,null,[[e,"Sponsored.Lionsgate.Wonder.Book Page.Movie Edition"]],
[[g,"c","book/show/31410964-wonder"]]],[b,null,[[e,"Sponsored.Lionsgate.Wonder.Book Page.Default"]],[[g,"c","book/show/11387515-wonder"]]],[b,null,[[e,"Sponsored.Comcast.Comcast NE Q3.Special Section: Back to School"]],[[g,"c","book_movie_challenges/show/7023"]]],[b,null,[[e,"Sponsored.Special Section.Books to Screen"]],[[g,"c","book_movie_challenges/show/6982"]]],[b,null,[[e,"Sponsored.Special Section.Family Memoirs"]],[[g,"c","book_movie_challenges/show/6963"]]],[b,null,[[e,"to-read"]],[[g,"c",
"shelf"],[g,"c","to-read"]]],[b,null,[[e,"currently-reading"]],[[g,"c","shelf"],[g,"c","currently-reading"]]],[b,null,[[e,"read"]],[[g,"c","shelf"],[g,"c","read"],[g,"nc","to-"],[g,"nc","currently-reading"]]],[b,null,[[e,"Goodreads.Special Sections.Books to Film 2017"]],[[g,"c","book_movie_challenges/show/5518"]]],[b,null,[[e,"Genre.Romance"]],[[t,"c","/genres/romance"]]],[b,null,[[e,"Genre.Fantasy"]],[[t,"eq","/genres/fantasy"]]],[b,null,[[e,"Genre.YoungAdult"]],[[t,"eq","/genres/young-adult"]]],
[b,null,[[e,"Genre.GenreMainPage"]],[[t,"eq","/genres"]]],[b,null,[[e,"Genre.ScienceFiction"]],[[t,"eq","/genres/science-fiction"]]],[b,null,[[e,"Goodreads.Special Sections.Inspirational Journeys"]],[[t,"c","book_movie_challenges/show/6172"]]],[b,null,[[e,"Genre.GoodreadsBlog"]],[[t,"c","/blog/index"]]],[b,null,[[e,"Genre.Audible"]],[[t,"eq","/audible"]]],[b,null,[[e,"Goodreads.Challenges.A Monster Calls"]],[[t,"c","/book_movie_challenges/show/5495"]]],[b,null,[[function(b,e){var g=[],f;if("array"===
I(e)){for(f=0;f<e.length;f++)g.push(b+"."+e[f]);return v(g.join(","))}return v(b+"."+e)},"Genre"]],[[function(b,e,g){e=document.getElementsByTagName("meta");for(var f,m,n=0;n<e.length;n++)if(f=e[n],m=f.getAttribute("name")||f.getAttribute("property"),m==g){e=f.getAttribute("content");f=m=f=void 0;b:{f=void 0;for(f=0;f<z.length;f++)if(z[f]===g){f=!1;break b}f=!0}if(e)if(f){m=e.split(",");for(f=0;f<m.length;f++)m[f]=E(m[f]);g=m}else g=E(e.replace(/,+/g," "));else g=e;b(g);return}b(!1)},"exactmatch",
"twitter:title"],[g,"c","goodreads.com/genres"]]],[b,null,[[e,"Sponsored.Challenges.Come Sundown"]],[[g,"c","book_movie_challenges/show/6570"]]],[b,null,[[e,"Sponsored.Special Section.Books to Broadway"]],[[g,"c","book_movie_challenges/show/6773"]]],[b,null,[[e,"Sponsored.Special Section.Summer Reading"]],[[g,"c","book_movie_challenges/show/4525"]]],[b,null,[[e,"Sponsored"]],[[g,"c","book_movie_challenges/"]]],[b,null,[[e,"Sponsored.Special Section.Inspirational Journeys"]],[[g,"c","book_movie_challenges/show/6172"]]],
[b,null,[[e,"Sponsored.Special Section.Books to Film 2017"]],[[g,"c","book_movie_challenges/show/5518"]]],[b,null,[[e,"Genre.Blog"]],[[g,"c","/blog"]]],[b,null,[[e,"Genre.Blog.summer"]],[[g,"c","summer"],[g,"c","/blog"]]]])}("p-0dUe_kJAjvkoY",window,document)}catch(nfe$$3){}quantserve();